# Generated by mojo_bindgen - do not edit by hand.
# source: /home/mmabrouk/Documents/Projects/hts_mojo/vendor/htslib/hts.h
# library: hts  link_name: hts
# FFI mode: external_call

from std.ffi import external_call, DEFAULT_RTLD, OwnedDLHandle, UnsafeUnion, c_char, c_double, c_float, c_int, c_long, c_long_long, c_short, c_uchar, c_uint, c_ulong, c_ushort, c_size_t
from std.ffi import CStringSlice
from std.memory import ImmutOpaquePointer, MutOpaquePointer
from std.sys.info import size_of

# macro hts_expand: function-like macros are preserved but not parsed



comptime c_void_ptr = UnsafePointer[NoneType, MutExternalOrigin]


# define hts_expand ( type_t , n , m , ptr ) do { if ( ( n ) > ( m ) ) 
#{ size_t hts_realloc_or_die ( size_t , size_t , size_t , size_t , int , void * * , const char * ) ;
# ( m ) = hts_realloc_or_die ( ( n ) >= 1 ? ( n ) : 1 , ( m ) , sizeof ( m ) , sizeof ( type_t ) , 0 , ( void * * ) & ( ptr ) , __func__ ) ;
# } } while ( 0 )


def hts_realloc_or_die(
    n: c_size_t,
    m: c_size_t,
    size_m: c_size_t,
    size_t: c_size_t,
    clear: c_int,
    ptr: UnsafePointer[c_void_ptr, MutExternalOrigin],
    func: UnsafePointer[UInt8, MutExternalOrigin],
) abi("C") -> c_size_t:
    return  external_call["hts_realloc_or_die",
        c_size_t,
        c_size_t,
        c_size_t,
        c_size_t,
        c_size_t,
        c_int,
        UnsafePointer[c_void_ptr, MutExternalOrigin],
        UnsafePointer[UInt8, MutExternalOrigin],
    ](n, m, size_m, size_t, clear, ptr, func)


def hts_expand[T: AnyType](
    n: c_size_t,
    mut m: c_size_t,
    ptr: UnsafePointer[UnsafePointer[T, MutExternalOrigin], MutExternalOrigin],
) raises abi("C") -> c_size_t:
    if n > m:
        var requested = n
        if requested < 1:
            requested = 1

        # Equivalent of `(void **)&ptr`
        var void_pp = ptr.bitcast[c_void_ptr]()

        m = hts_realloc_or_die(
            requested,
            m,
            UInt(size_of[c_size_t]()),
            UInt(size_of[T]()),
            0,
            void_pp,
            CStringSlice("hts_expand").as_bytes_with_nul().unsafe_ptr().unsafe_mut_cast[True]().unsafe_origin_cast[MutExternalOrigin](),
        )

    return m




# macro hts_expand0: function-like macros are preserved but not parsed
# define hts_expand0 ( type_t , n , m , ptr ) do { if ( ( n ) > ( m ) ) { size_t hts_realloc_or_die ( size_t , size_t , size_t , size_t , int , void * * , const char * ) ; ( m ) = hts_realloc_or_die ( ( n ) >= 1 ? ( n ) : 1 , ( m ) , sizeof ( m ) , sizeof ( type_t ) , 1 , ( void * * ) & ( ptr ) , __func__ ) ; } } while ( 0 )

def hts_expand0[T: AnyType](
    n: c_size_t,
    mut m: c_size_t,
    ptr: UnsafePointer[UnsafePointer[T, MutExternalOrigin], MutExternalOrigin],
) raises abi("C") -> c_size_t:
    if n > m:
        var requested = n
        if requested < 1:
            requested = 1

        # reinterpret (T**) as (void**)
        var void_pp = ptr.bitcast[c_void_ptr]()

        m = hts_realloc_or_die(
            requested,
            m,
            UInt(size_of[c_size_t]()),
            UInt(size_of[T]()),
            1,  # <-- zero-initialize (difference vs hts_expand)
            void_pp,
            CStringSlice("hts_expand0").as_bytes_with_nul().unsafe_ptr().unsafe_mut_cast[True]().unsafe_origin_cast[MutExternalOrigin](),
        )

    return m



# macro hts_resize: function-like macros are preserved but not parsed
# define hts_resize ( type_t , num , size_ptr , ptr , flags ) ( ( num ) > ( * ( size_ptr ) ) ? hts_resize_array_ ( sizeof ( type_t ) , ( num ) , sizeof ( * ( size_ptr ) ) , ( size_ptr ) , ( void * * ) ( ptr ) , ( flags ) , __func__ ) : 0 )
def hts_resize_array_(
    item_size: c_size_t,
    num: c_size_t,
    size_size: c_size_t,
    size_ptr: UnsafePointer[c_size_t, MutExternalOrigin],
    ptr: UnsafePointer[c_void_ptr, MutExternalOrigin],
    flags: c_int,
    func: UnsafePointer[c_char, ImmutExternalOrigin],
) -> c_int:
    return external_call[
        "hts_resize_array_",
        c_int,
        c_size_t,
        c_size_t,
        c_size_t,
        UnsafePointer[c_size_t, MutExternalOrigin],
        UnsafePointer[c_void_ptr, MutExternalOrigin],
        c_int,
        UnsafePointer[c_char, ImmutExternalOrigin],
    ](item_size, num, size_size, size_ptr, ptr, flags, func)


def hts_resize[T: AnyType](
    num: c_size_t,
    size_ptr: UnsafePointer[c_size_t, MutExternalOrigin],
    ptr: UnsafePointer[c_void_ptr, MutExternalOrigin],
    flags: c_int,
) raises abi("C") -> c_int:
    if num > size_ptr[]:
        return hts_resize_array_(
            UInt(size_of[T]()),
            num,
            UInt(size_of[c_size_t]()),
            size_ptr,
            ptr,
            flags,
            (CStringSlice("hts_resize")
            .as_bytes_with_nul()
            .unsafe_ptr()
            .unsafe_mut_cast[False]()
            .unsafe_origin_cast[ImmutExternalOrigin]()
            .bitcast[Int8]()
            ),
        )

    return 0

# macro cram_option: identifier reference macro is not emitted directly; only literal macros are currently supported
comptime cram_option = hts_fmt_option

# macro HTS_FILE_OPTS_INIT: unsupported macro replacement list
# define HTS_FILE_OPTS_INIT { { 0 } , 0 }

# macro HTS_POS_MAX: unsupported macro replacement list
# define HTS_POS_MAX ( ( ( ( int64_t ) INT_MAX ) << 32 ) | INT_MAX )

# macro HTS_POS_MIN: unsupported macro replacement list
# define HTS_POS_MIN INT64_MIN
comptime HTS_POS_MAX: Int64 = 9223372036854775807
comptime HTS_POS_MIN: Int64 = -9223372036854775808


# macro PRIhts_pos: unsupported macro replacement list
# define PRIhts_pos PRId64
comptime PRIhts_pos = "d"

# macro hts_bin_first: function-like macros are preserved but not parsed
# define hts_bin_first ( l ) ( ( ( 1 << ( ( ( l ) << 1 ) + ( l ) ) ) - 1 ) / 7 )

def hts_bin_first(l: Int) -> Int:
    return ((1 << ((l << 1) + l)) - 1) // 7


# macro hts_bin_parent: function-like macros are preserved but not parsed
# define hts_bin_parent ( b ) ( ( ( b ) - 1 ) >> 3 )
def hts_bin_parent(b: Int) -> Int:
    return (b - 1) >> 3

# macro hts_itr_multi_destroy: function-like macros are preserved but not parsed
# define hts_itr_multi_destroy ( iter ) hts_itr_destroy ( iter )
def hts_itr_multi_destroy(iter: UnsafePointer[hts_itr_t, MutExternalOrigin]):
    hts_itr_destroy(iter)

# Resolve symbols from libraries already linked into this process.
def _bindgen_dl() raises -> OwnedDLHandle:
    return OwnedDLHandle(DEFAULT_RTLD)

struct GlobalVar[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))
        if not opt:
            raise Error(String("bindgen: missing C global symbol"))
        return opt.value()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, MutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()

    @staticmethod
    def store(value: Self.T) raises -> None:
        var p = rebind[UnsafePointer[Self.T, MutExternalOrigin]](Self._raw())
        p[] = value.copy()

struct GlobalConst[T: Copyable & ImplicitlyDestructible, //, link: StaticString]:
    @staticmethod
    def _raw() raises -> UnsafePointer[Self.T, MutAnyOrigin]:
        var opt: Optional[UnsafePointer[Self.T, MutAnyOrigin]] = _bindgen_dl().get_symbol[Self.T](StringSlice(Self.link))
        if not opt:
            raise Error(String("bindgen: missing C global symbol"))
        return opt.value()

    @staticmethod
    def ptr() raises -> UnsafePointer[Self.T, ImmutExternalOrigin]:
        return rebind[UnsafePointer[Self.T, ImmutExternalOrigin]](Self._raw())

    @staticmethod
    def load() raises -> Self.T:
        return Self._raw()[].copy()

comptime hts_itr_t_readrec_cb = def (arg0: UnsafePointer[BGZF, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: MutOpaquePointer[MutExternalOrigin], arg3: UnsafePointer[c_int, MutExternalOrigin], arg4: UnsafePointer[c_long, MutExternalOrigin], arg5: UnsafePointer[c_long, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_t_seek_cb = def (arg0: MutOpaquePointer[MutExternalOrigin], arg1: c_long, arg2: c_int) thin abi("C") -> c_int

comptime hts_itr_t_tell_cb = def (arg0: MutOpaquePointer[MutExternalOrigin]) thin abi("C") -> c_long

comptime hts_itr_query_readrec_cb = def (arg0: UnsafePointer[BGZF, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: MutOpaquePointer[MutExternalOrigin], arg3: UnsafePointer[c_int, MutExternalOrigin], arg4: UnsafePointer[c_long, MutExternalOrigin], arg5: UnsafePointer[c_long, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_query_func_readrec_cb = def (arg0: UnsafePointer[BGZF, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: MutOpaquePointer[MutExternalOrigin], arg3: UnsafePointer[c_int, MutExternalOrigin], arg4: UnsafePointer[c_long, MutExternalOrigin], arg5: UnsafePointer[c_long, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_querys_itr_query_arg4_cb = def (arg0: UnsafePointer[BGZF, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: MutOpaquePointer[MutExternalOrigin], arg3: UnsafePointer[c_int, MutExternalOrigin], arg4: UnsafePointer[c_long, MutExternalOrigin], arg5: UnsafePointer[c_long, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_querys_itr_query_cb = def (arg0: UnsafePointer[hts_idx_t, ImmutExternalOrigin], arg1: c_int, arg2: c_long, arg3: c_long, arg4: hts_itr_querys_itr_query_arg4_cb) thin abi("C") -> UnsafePointer[hts_itr_t, MutExternalOrigin]

comptime hts_itr_querys_readrec_cb = def (arg0: UnsafePointer[BGZF, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: MutOpaquePointer[MutExternalOrigin], arg3: UnsafePointer[c_int, MutExternalOrigin], arg4: UnsafePointer[c_long, MutExternalOrigin], arg5: UnsafePointer[c_long, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_regions_itr_specific_cb = def (arg0: UnsafePointer[hts_idx_t, ImmutExternalOrigin], arg1: UnsafePointer[hts_itr_t, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_regions_readrec_cb = def (arg0: UnsafePointer[BGZF, MutExternalOrigin], arg1: MutOpaquePointer[MutExternalOrigin], arg2: MutOpaquePointer[MutExternalOrigin], arg3: UnsafePointer[c_int, MutExternalOrigin], arg4: UnsafePointer[c_long, MutExternalOrigin], arg5: UnsafePointer[c_long, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_regions_seek_cb = def (arg0: MutOpaquePointer[MutExternalOrigin], arg1: c_long, arg2: c_int) thin abi("C") -> c_int

comptime hts_itr_regions_tell_cb = def (arg0: MutOpaquePointer[MutExternalOrigin]) thin abi("C") -> c_long

comptime size_t = UInt

comptime int64_t = Int64

comptime uint64_t = UInt64

comptime uint32_t = UInt32

comptime uint8_t = UInt8

comptime uint16_t = UInt16

comptime htsFile__anon_union_1 = UnsafeUnion[UnsafePointer[BGZF, MutExternalOrigin], UnsafePointer[cram_fd, MutExternalOrigin], UnsafePointer[hFILE, MutExternalOrigin]]

comptime hts_opt__anon_union_1 = UnsafeUnion[c_int, UnsafePointer[c_char, MutExternalOrigin]]

comptime hts_pos_t = int64_t

comptime hts_pair32_t = hts_pair_pos_t

comptime hts_readrec_func = def (fp: UnsafePointer[BGZF, MutExternalOrigin], data: MutOpaquePointer[MutExternalOrigin], r: MutOpaquePointer[MutExternalOrigin], tid: UnsafePointer[c_int, MutExternalOrigin], beg: UnsafePointer[hts_pos_t, MutExternalOrigin], end: UnsafePointer[hts_pos_t, MutExternalOrigin]) thin abi("C") -> c_int

comptime hts_seek_func = def (fp: MutOpaquePointer[MutExternalOrigin], offset: int64_t, where: c_int) thin abi("C") -> c_int

comptime hts_tell_func = def (fp: MutOpaquePointer[MutExternalOrigin]) thin abi("C") -> int64_t

comptime hts_itr_multi_t = hts_itr_t

comptime hts_id2name_f = def (arg0: MutOpaquePointer[MutExternalOrigin], arg1: c_int) thin abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]

comptime hts_name2id_f = def (arg0: MutOpaquePointer[MutExternalOrigin], arg1: UnsafePointer[c_char, ImmutExternalOrigin]) thin abi("C") -> c_int

comptime hts_itr_query_func = def (idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], tid: c_int, beg: hts_pos_t, end: hts_pos_t, readrec: hts_itr_query_func_readrec_cb) thin abi("C") -> UnsafePointer[hts_itr_t, MutExternalOrigin]

comptime hts_itr_multi_query_func = def (idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], itr: UnsafePointer[hts_itr_t, MutExternalOrigin]) thin abi("C") -> c_int

comptime HTS_PATH_SEPARATOR_CHAR = ':'

comptime HTS_PATH_SEPARATOR_STR = ":"


comptime HTS_RESIZE_CLEAR = c_int(1)

comptime HTS_IDX_DELIM = "##idx##"

comptime HTS_VERSION = c_int(102390)

comptime HTS_FEATURE_CONFIGURE = c_int(1)

comptime HTS_FEATURE_PLUGINS = c_int(2)

comptime HTS_FEATURE_LIBCURL = c_uint(1024)

comptime HTS_FEATURE_S3 = c_uint(2048)

comptime HTS_FEATURE_GCS = c_uint(4096)

comptime HTS_FEATURE_LIBDEFLATE = c_uint(1048576)

comptime HTS_FEATURE_LZMA = c_uint(2097152)

comptime HTS_FEATURE_BZIP2 = c_uint(4194304)

comptime HTS_FEATURE_HTSCODECS = c_uint(8388608)

comptime HTS_FEATURE_CC = c_uint(134217728)

comptime HTS_FEATURE_CFLAGS = c_uint(268435456)

comptime HTS_FEATURE_CPPFLAGS = c_uint(536870912)

comptime HTS_FEATURE_LDFLAGS = c_uint(1073741824)

comptime HTS_IDX_NOCOOR = c_int(-2)

comptime HTS_IDX_START = c_int(-3)

comptime HTS_IDX_REST = c_int(-4)

comptime HTS_IDX_NONE = c_int(-5)

comptime HTS_FMT_CSI = c_int(0)

comptime HTS_FMT_BAI = c_int(1)

comptime HTS_FMT_TBI = c_int(2)

comptime HTS_FMT_CRAI = c_int(3)

comptime HTS_FMT_FAI = c_int(4)


comptime HTS_IDX_SAVE_REMOTE = c_int(1)

comptime HTS_IDX_SILENT_FAIL = c_int(2)

comptime HTS_PARSE_THOUSANDS_SEP = c_int(1)

comptime HTS_PARSE_ONE_COORD = c_int(2)

comptime HTS_PARSE_LIST = c_int(4)


comptime FT_UNKN = c_int(0)

comptime FT_GZ = c_int(1)

comptime FT_VCF = c_int(2)

comptime FT_VCF_GZ = c_int(3)

comptime FT_BCF = c_int(4)

comptime FT_BCF_GZ = c_int(5)

comptime FT_STDIN = c_int(8)

struct kstring_t(Copyable, Movable):
    pass

struct BGZF(Copyable, Movable):
    pass

struct cram_fd(Copyable, Movable):
    pass

struct hFILE(Copyable, Movable):
    pass

struct hts_tpool(Copyable, Movable):
    pass

struct sam_hdr_t(Copyable, Movable):
    pass

@fieldwise_init
struct htsFormatCategory(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime unknown_category = Self(c_uint(0))
    comptime sequence_data = Self(c_uint(1))
    comptime variant_data = Self(c_uint(2))
    comptime index_file = Self(c_uint(3))
    comptime region_list = Self(c_uint(4))
    comptime category_maximum = Self(c_uint(32767))

@fieldwise_init
struct htsExactFormat(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime unknown_format = Self(c_uint(0))
    comptime binary_format = Self(c_uint(1))
    comptime text_format = Self(c_uint(2))
    comptime sam = Self(c_uint(3))
    comptime bam = Self(c_uint(4))
    comptime bai = Self(c_uint(5))
    comptime cram = Self(c_uint(6))
    comptime crai = Self(c_uint(7))
    comptime vcf = Self(c_uint(8))
    comptime bcf = Self(c_uint(9))
    comptime csi = Self(c_uint(10))
    comptime gzi = Self(c_uint(11))
    comptime tbi = Self(c_uint(12))
    comptime bed = Self(c_uint(13))
    comptime htsget = Self(c_uint(14))
    comptime json = Self(c_uint(14))
    comptime empty_format = Self(c_uint(15))
    comptime fasta_format = Self(c_uint(16))
    comptime fastq_format = Self(c_uint(17))
    comptime fai_format = Self(c_uint(18))
    comptime fqi_format = Self(c_uint(19))
    comptime hts_crypt4gh_format = Self(c_uint(20))
    comptime d4_format = Self(c_uint(21))
    comptime format_maximum = Self(c_uint(32767))

@fieldwise_init
struct htsCompression(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime no_compression = Self(c_uint(0))
    comptime gzip = Self(c_uint(1))
    comptime bgzf = Self(c_uint(2))
    comptime custom = Self(c_uint(3))
    comptime bzip2_compression = Self(c_uint(4))
    comptime razf_compression = Self(c_uint(5))
    comptime xz_compression = Self(c_uint(6))
    comptime zstd_compression = Self(c_uint(7))
    comptime compression_maximum = Self(c_uint(32767))

@align(2)
@fieldwise_init
struct htsFormat__anon_struct_1(TrivialRegisterPassable):
    var major: c_short
    var minor: c_short

@align(8)
@fieldwise_init
struct htsFormat(Copyable, Movable):
    var category: htsFormatCategory
    var format: htsExactFormat
    var version: htsFormat__anon_struct_1
    var compression: htsCompression
    var compression_level: c_short
    var specific: MutOpaquePointer[MutExternalOrigin]

struct hts_idx_t(Copyable, Movable):
    pass

struct hts_filter_t(Copyable, Movable):
    pass

@align(8)
@fieldwise_init
struct htsFile(Copyable, Movable):
    var __pad0: InlineArray[UInt8, 8]
    var lineno: int64_t
    var line: kstring_t
    var fn_: UnsafePointer[c_char, MutExternalOrigin]
    var fn_aux: UnsafePointer[c_char, MutExternalOrigin]
    var fp: htsFile__anon_union_1
    var state: MutOpaquePointer[MutExternalOrigin]
    var format: htsFormat
    var idx: UnsafePointer[hts_idx_t, MutExternalOrigin]
    var fnidx: UnsafePointer[c_char, ImmutExternalOrigin]
    var bam_header: UnsafePointer[sam_hdr_t, MutExternalOrigin]
    var filter: UnsafePointer[hts_filter_t, MutExternalOrigin]

@align(8)
@fieldwise_init
struct htsThreadPool(TrivialRegisterPassable):
    var pool: UnsafePointer[hts_tpool, MutExternalOrigin]
    var qsize: c_int

@fieldwise_init
struct sam_fields(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime SAM_QNAME = Self(c_uint(1))
    comptime SAM_FLAG = Self(c_uint(2))
    comptime SAM_RNAME = Self(c_uint(4))
    comptime SAM_POS = Self(c_uint(8))
    comptime SAM_MAPQ = Self(c_uint(16))
    comptime SAM_CIGAR = Self(c_uint(32))
    comptime SAM_RNEXT = Self(c_uint(64))
    comptime SAM_PNEXT = Self(c_uint(128))
    comptime SAM_TLEN = Self(c_uint(256))
    comptime SAM_SEQ = Self(c_uint(512))
    comptime SAM_QUAL = Self(c_uint(1024))
    comptime SAM_AUX = Self(c_uint(2048))
    comptime SAM_RGAUX = Self(c_uint(4096))

@fieldwise_init
struct hts_fmt_option(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime CRAM_OPT_DECODE_MD = Self(c_uint(0))
    comptime CRAM_OPT_PREFIX = Self(c_uint(1))
    comptime CRAM_OPT_VERBOSITY = Self(c_uint(2))
    comptime CRAM_OPT_SEQS_PER_SLICE = Self(c_uint(3))
    comptime CRAM_OPT_SLICES_PER_CONTAINER = Self(c_uint(4))
    comptime CRAM_OPT_RANGE = Self(c_uint(5))
    comptime CRAM_OPT_VERSION = Self(c_uint(6))
    comptime CRAM_OPT_EMBED_REF = Self(c_uint(7))
    comptime CRAM_OPT_IGNORE_MD5 = Self(c_uint(8))
    comptime CRAM_OPT_REFERENCE = Self(c_uint(9))
    comptime CRAM_OPT_MULTI_SEQ_PER_SLICE = Self(c_uint(10))
    comptime CRAM_OPT_NO_REF = Self(c_uint(11))
    comptime CRAM_OPT_USE_BZIP2 = Self(c_uint(12))
    comptime CRAM_OPT_SHARED_REF = Self(c_uint(13))
    comptime CRAM_OPT_NTHREADS = Self(c_uint(14))
    comptime CRAM_OPT_THREAD_POOL = Self(c_uint(15))
    comptime CRAM_OPT_USE_LZMA = Self(c_uint(16))
    comptime CRAM_OPT_USE_RANS = Self(c_uint(17))
    comptime CRAM_OPT_REQUIRED_FIELDS = Self(c_uint(18))
    comptime CRAM_OPT_LOSSY_NAMES = Self(c_uint(19))
    comptime CRAM_OPT_BASES_PER_SLICE = Self(c_uint(20))
    comptime CRAM_OPT_STORE_MD = Self(c_uint(21))
    comptime CRAM_OPT_STORE_NM = Self(c_uint(22))
    comptime CRAM_OPT_RANGE_NOSEEK = Self(c_uint(23))
    comptime CRAM_OPT_USE_TOK = Self(c_uint(24))
    comptime CRAM_OPT_USE_FQZ = Self(c_uint(25))
    comptime CRAM_OPT_USE_ARITH = Self(c_uint(26))
    comptime CRAM_OPT_POS_DELTA = Self(c_uint(27))
    comptime HTS_OPT_COMPRESSION_LEVEL = Self(c_uint(100))
    comptime HTS_OPT_NTHREADS = Self(c_uint(101))
    comptime HTS_OPT_THREAD_POOL = Self(c_uint(102))
    comptime HTS_OPT_CACHE_SIZE = Self(c_uint(103))
    comptime HTS_OPT_BLOCK_SIZE = Self(c_uint(104))
    comptime HTS_OPT_FILTER = Self(c_uint(105))
    comptime HTS_OPT_PROFILE = Self(c_uint(106))
    comptime FASTQ_OPT_CASAVA = Self(c_uint(1000))
    comptime FASTQ_OPT_AUX = Self(c_uint(1001))
    comptime FASTQ_OPT_RNUM = Self(c_uint(1002))
    comptime FASTQ_OPT_BARCODE = Self(c_uint(1003))
    comptime FASTQ_OPT_NAME2 = Self(c_uint(1004))
    comptime FASTQ_OPT_UMI = Self(c_uint(1005))
    comptime FASTQ_OPT_UMI_REGEX = Self(c_uint(1006))

@fieldwise_init
struct hts_profile_option(Copyable, Movable, RegisterPassable):
    var value: c_uint
    comptime HTS_PROFILE_FAST = Self(c_uint(0))
    comptime HTS_PROFILE_NORMAL = Self(c_uint(1))
    comptime HTS_PROFILE_SMALL = Self(c_uint(2))
    comptime HTS_PROFILE_ARCHIVE = Self(c_uint(3))

@align(8)
@fieldwise_init
struct hts_opt(Copyable, Movable):
    var arg: UnsafePointer[c_char, MutExternalOrigin]
    var opt: hts_fmt_option
    var val: hts_opt__anon_union_1
    var next: UnsafePointer[hts_opt, MutExternalOrigin]

@align(8)
@fieldwise_init
struct hts_pair_pos_t(TrivialRegisterPassable):
    var beg: hts_pos_t
    var end: hts_pos_t

@align(8)
@fieldwise_init
struct hts_pair64_t(TrivialRegisterPassable):
    var u: uint64_t
    var v: uint64_t

@align(8)
@fieldwise_init
struct hts_pair64_max_t(TrivialRegisterPassable):
    var u: uint64_t
    var v: uint64_t
    var max: uint64_t

@align(8)
@fieldwise_init
struct hts_reglist_t(TrivialRegisterPassable):
    var reg: UnsafePointer[c_char, ImmutExternalOrigin]
    var intervals: UnsafePointer[hts_pair_pos_t, MutExternalOrigin]
    var tid: c_int
    var count: uint32_t
    var min_beg: hts_pos_t
    var max_end: hts_pos_t

@align(8)
@fieldwise_init
struct hts_itr_t__anon_struct_1(TrivialRegisterPassable):
    var n: c_int
    var m: c_int
    var a: UnsafePointer[c_int, MutExternalOrigin]

@align(8)
@fieldwise_init
struct hts_itr_t(Copyable, Movable):
    var __pad0: InlineArray[UInt8, 4]
    var tid: c_int
    var n_off: c_int
    var i: c_int
    var n_reg: c_int
    var beg: hts_pos_t
    var end: hts_pos_t
    var reg_list: UnsafePointer[hts_reglist_t, MutExternalOrigin]
    var curr_tid: c_int
    var curr_reg: c_int
    var curr_intv: c_int
    var curr_beg: hts_pos_t
    var curr_end: hts_pos_t
    var curr_off: uint64_t
    var nocoor_off: uint64_t
    var off: UnsafePointer[hts_pair64_max_t, MutExternalOrigin]
    var readrec: hts_itr_t_readrec_cb
    var seek: hts_itr_t_seek_cb
    var tell: hts_itr_t_tell_cb
    var bins: hts_itr_t__anon_struct_1

struct errmod_t(Copyable, Movable):
    pass

@align(4)
@fieldwise_init
struct probaln_par_t(TrivialRegisterPassable):
    var d: c_float
    var e: c_float
    var bw: c_int

struct hts_md5_context(Copyable, Movable):
    pass

# global `seq_nt16_table` -> InlineArray[c_uchar, 256]
comptime seq_nt16_table = GlobalVar[T=InlineArray[c_uchar, 256], link="seq_nt16_table"]

# global `seq_nt16_str` -> UnsafePointer[c_char, MutExternalOrigin]
comptime seq_nt16_str = GlobalVar[T=UnsafePointer[c_char, MutExternalOrigin], link="seq_nt16_str"]

# global `seq_nt16_int` -> UnsafePointer[c_int, MutExternalOrigin]
comptime seq_nt16_int = GlobalVar[T=UnsafePointer[c_int, MutExternalOrigin], link="seq_nt16_int"]

def hts_resize_array_(a0: size_t, a1: size_t, a2: size_t, a3: MutOpaquePointer[MutExternalOrigin], a4: UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin], a5: c_int, a6: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_resize_array_", c_int, size_t, size_t, size_t, MutOpaquePointer[MutExternalOrigin], UnsafePointer[MutOpaquePointer[MutExternalOrigin], MutExternalOrigin], c_int, UnsafePointer[c_char, ImmutExternalOrigin]](a0, a1, a2, a3, a4, a5, a6)

def hts_lib_shutdown() abi("C") -> None:
    external_call["hts_lib_shutdown", NoneType]()

def hts_free(ptr: MutOpaquePointer[MutExternalOrigin]) abi("C") -> None:
    external_call["hts_free", NoneType, MutOpaquePointer[MutExternalOrigin]](ptr)

def hts_opt_add(opts: UnsafePointer[UnsafePointer[hts_opt, MutExternalOrigin], MutExternalOrigin], c_arg: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_opt_add", c_int, UnsafePointer[UnsafePointer[hts_opt, MutExternalOrigin], MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](opts, c_arg)

def hts_opt_apply(fp: UnsafePointer[htsFile, MutExternalOrigin], opts: UnsafePointer[hts_opt, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_opt_apply", c_int, UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[hts_opt, MutExternalOrigin]](fp, opts)

def hts_opt_free(opts: UnsafePointer[hts_opt, MutExternalOrigin]) abi("C") -> None:
    external_call["hts_opt_free", NoneType, UnsafePointer[hts_opt, MutExternalOrigin]](opts)

def hts_parse_format(opt: UnsafePointer[htsFormat, MutExternalOrigin], str: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_parse_format", c_int, UnsafePointer[htsFormat, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](opt, str)

def hts_parse_opt_list(opt: UnsafePointer[htsFormat, MutExternalOrigin], str: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_parse_opt_list", c_int, UnsafePointer[htsFormat, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](opt, str)

def hts_version() abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["hts_version", UnsafePointer[c_char, ImmutExternalOrigin]]()

def hts_features() abi("C") -> c_uint:
    return external_call["hts_features", c_uint]()

def hts_test_feature(id: c_uint) abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["hts_test_feature", UnsafePointer[c_char, ImmutExternalOrigin], c_uint](id)

def hts_feature_string() abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["hts_feature_string", UnsafePointer[c_char, ImmutExternalOrigin]]()

def hts_detect_format(fp: UnsafePointer[hFILE, MutExternalOrigin], fmt: UnsafePointer[htsFormat, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_detect_format", c_int, UnsafePointer[hFILE, MutExternalOrigin], UnsafePointer[htsFormat, MutExternalOrigin]](fp, fmt)

def hts_detect_format2(fp: UnsafePointer[hFILE, MutExternalOrigin], fname: UnsafePointer[c_char, ImmutExternalOrigin], fmt: UnsafePointer[htsFormat, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_detect_format2", c_int, UnsafePointer[hFILE, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[htsFormat, MutExternalOrigin]](fp, fname, fmt)

def hts_format_description(format: UnsafePointer[htsFormat, ImmutExternalOrigin]) abi("C") -> UnsafePointer[c_char, MutExternalOrigin]:
    return external_call["hts_format_description", UnsafePointer[c_char, MutExternalOrigin], UnsafePointer[htsFormat, ImmutExternalOrigin]](format)

def hts_open(fn_: UnsafePointer[c_char, ImmutExternalOrigin], mode: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> UnsafePointer[htsFile, MutExternalOrigin]:
    return external_call["hts_open", UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](fn_, mode)

def hts_open_format(fn_: UnsafePointer[c_char, ImmutExternalOrigin], mode: UnsafePointer[c_char, ImmutExternalOrigin], fmt: UnsafePointer[htsFormat, ImmutExternalOrigin]) abi("C") -> UnsafePointer[htsFile, MutExternalOrigin]:
    return external_call["hts_open_format", UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[htsFormat, ImmutExternalOrigin]](fn_, mode, fmt)

def hts_hopen(fp: UnsafePointer[hFILE, MutExternalOrigin], fn_: UnsafePointer[c_char, ImmutExternalOrigin], mode: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> UnsafePointer[htsFile, MutExternalOrigin]:
    return external_call["hts_hopen", UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[hFILE, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](fp, fn_, mode)

def hts_flush(fp: UnsafePointer[htsFile, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_flush", c_int, UnsafePointer[htsFile, MutExternalOrigin]](fp)

def hts_close(fp: UnsafePointer[htsFile, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_close", c_int, UnsafePointer[htsFile, MutExternalOrigin]](fp)

def hts_get_format(fp: UnsafePointer[htsFile, MutExternalOrigin]) abi("C") -> UnsafePointer[htsFormat, ImmutExternalOrigin]:
    return external_call["hts_get_format", UnsafePointer[htsFormat, ImmutExternalOrigin], UnsafePointer[htsFile, MutExternalOrigin]](fp)

def hts_format_file_extension(format: UnsafePointer[htsFormat, ImmutExternalOrigin]) abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["hts_format_file_extension", UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[htsFormat, ImmutExternalOrigin]](format)

# variadic C function - not callable from thin FFI:
# c_int hts_set_opt(fp: UnsafePointer[htsFile, MutExternalOrigin], opt: hts_fmt_option, ...)

def hts_getline(fp: UnsafePointer[htsFile, MutExternalOrigin], delimiter: c_int, str: UnsafePointer[kstring_t, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_getline", c_int, UnsafePointer[htsFile, MutExternalOrigin], c_int, UnsafePointer[kstring_t, MutExternalOrigin]](fp, delimiter, str)

def hts_readlines(fn_: UnsafePointer[c_char, ImmutExternalOrigin], _n: UnsafePointer[c_int, MutExternalOrigin]) abi("C") -> UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin]:
    return external_call["hts_readlines", UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin]](fn_, _n)

def hts_readlist(fn_: UnsafePointer[c_char, ImmutExternalOrigin], is_file: c_int, _n: UnsafePointer[c_int, MutExternalOrigin]) abi("C") -> UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin]:
    return external_call["hts_readlist", UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], c_int, UnsafePointer[c_int, MutExternalOrigin]](fn_, is_file, _n)

def hts_set_threads(fp: UnsafePointer[htsFile, MutExternalOrigin], n: c_int) abi("C") -> c_int:
    return external_call["hts_set_threads", c_int, UnsafePointer[htsFile, MutExternalOrigin], c_int](fp, n)

def hts_set_thread_pool(fp: UnsafePointer[htsFile, MutExternalOrigin], p: UnsafePointer[htsThreadPool, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_set_thread_pool", c_int, UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[htsThreadPool, MutExternalOrigin]](fp, p)

def hts_set_cache_size(fp: UnsafePointer[htsFile, MutExternalOrigin], n: c_int) abi("C") -> None:
    external_call["hts_set_cache_size", NoneType, UnsafePointer[htsFile, MutExternalOrigin], c_int](fp, n)

def hts_set_fai_filename(fp: UnsafePointer[htsFile, MutExternalOrigin], fn_aux: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_set_fai_filename", c_int, UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](fp, fn_aux)

def hts_set_filter_expression(fp: UnsafePointer[htsFile, MutExternalOrigin], expr: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_set_filter_expression", c_int, UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](fp, expr)

def hts_check_EOF(fp: UnsafePointer[htsFile, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_check_EOF", c_int, UnsafePointer[htsFile, MutExternalOrigin]](fp)

def hts_idx_init(n: c_int, fmt: c_int, offset0: uint64_t, min_shift: c_int, n_lvls: c_int) abi("C") -> UnsafePointer[hts_idx_t, MutExternalOrigin]:
    return external_call["hts_idx_init", UnsafePointer[hts_idx_t, MutExternalOrigin], c_int, c_int, uint64_t, c_int, c_int](n, fmt, offset0, min_shift, n_lvls)

def hts_idx_destroy(idx: UnsafePointer[hts_idx_t, MutExternalOrigin]) abi("C") -> None:
    external_call["hts_idx_destroy", NoneType, UnsafePointer[hts_idx_t, MutExternalOrigin]](idx)

def hts_idx_push(idx: UnsafePointer[hts_idx_t, MutExternalOrigin], tid: c_int, beg: hts_pos_t, end: hts_pos_t, offset: uint64_t, is_mapped: c_int) abi("C") -> c_int:
    return external_call["hts_idx_push", c_int, UnsafePointer[hts_idx_t, MutExternalOrigin], c_int, hts_pos_t, hts_pos_t, uint64_t, c_int](idx, tid, beg, end, offset, is_mapped)

def hts_idx_finish(idx: UnsafePointer[hts_idx_t, MutExternalOrigin], final_offset: uint64_t) abi("C") -> c_int:
    return external_call["hts_idx_finish", c_int, UnsafePointer[hts_idx_t, MutExternalOrigin], uint64_t](idx, final_offset)

def hts_idx_fmt(idx: UnsafePointer[hts_idx_t, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_idx_fmt", c_int, UnsafePointer[hts_idx_t, MutExternalOrigin]](idx)

def hts_idx_tbi_name(idx: UnsafePointer[hts_idx_t, MutExternalOrigin], tid: c_int, name: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_idx_tbi_name", c_int, UnsafePointer[hts_idx_t, MutExternalOrigin], c_int, UnsafePointer[c_char, ImmutExternalOrigin]](idx, tid, name)

def hts_idx_save(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], fn_: UnsafePointer[c_char, ImmutExternalOrigin], fmt: c_int) abi("C") -> c_int:
    return external_call["hts_idx_save", c_int, UnsafePointer[hts_idx_t, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], c_int](idx, fn_, fmt)

def hts_idx_save_as(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], fn_: UnsafePointer[c_char, ImmutExternalOrigin], fnidx: UnsafePointer[c_char, ImmutExternalOrigin], fmt: c_int) abi("C") -> c_int:
    return external_call["hts_idx_save_as", c_int, UnsafePointer[hts_idx_t, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], c_int](idx, fn_, fnidx, fmt)

def hts_idx_load(fn_: UnsafePointer[c_char, ImmutExternalOrigin], fmt: c_int) abi("C") -> UnsafePointer[hts_idx_t, MutExternalOrigin]:
    return external_call["hts_idx_load", UnsafePointer[hts_idx_t, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], c_int](fn_, fmt)

def hts_idx_load2(fn_: UnsafePointer[c_char, ImmutExternalOrigin], fnidx: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> UnsafePointer[hts_idx_t, MutExternalOrigin]:
    return external_call["hts_idx_load2", UnsafePointer[hts_idx_t, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin]](fn_, fnidx)

def hts_idx_load3(fn_: UnsafePointer[c_char, ImmutExternalOrigin], fnidx: UnsafePointer[c_char, ImmutExternalOrigin], fmt: c_int, flags: c_int) abi("C") -> UnsafePointer[hts_idx_t, MutExternalOrigin]:
    return external_call["hts_idx_load3", UnsafePointer[hts_idx_t, MutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], c_int, c_int](fn_, fnidx, fmt, flags)

def hts_idx_get_meta(idx: UnsafePointer[hts_idx_t, MutExternalOrigin], l_meta: UnsafePointer[uint32_t, MutExternalOrigin]) abi("C") -> UnsafePointer[uint8_t, MutExternalOrigin]:
    return external_call["hts_idx_get_meta", UnsafePointer[uint8_t, MutExternalOrigin], UnsafePointer[hts_idx_t, MutExternalOrigin], UnsafePointer[uint32_t, MutExternalOrigin]](idx, l_meta)

def hts_idx_set_meta(idx: UnsafePointer[hts_idx_t, MutExternalOrigin], l_meta: uint32_t, meta: UnsafePointer[uint8_t, MutExternalOrigin], is_copy: c_int) abi("C") -> c_int:
    return external_call["hts_idx_set_meta", c_int, UnsafePointer[hts_idx_t, MutExternalOrigin], uint32_t, UnsafePointer[uint8_t, MutExternalOrigin], c_int](idx, l_meta, meta, is_copy)

def hts_idx_get_stat(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], tid: c_int, mapped: UnsafePointer[uint64_t, MutExternalOrigin], unmapped: UnsafePointer[uint64_t, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_idx_get_stat", c_int, UnsafePointer[hts_idx_t, ImmutExternalOrigin], c_int, UnsafePointer[uint64_t, MutExternalOrigin], UnsafePointer[uint64_t, MutExternalOrigin]](idx, tid, mapped, unmapped)

def hts_idx_get_n_no_coor(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin]) abi("C") -> uint64_t:
    return external_call["hts_idx_get_n_no_coor", uint64_t, UnsafePointer[hts_idx_t, ImmutExternalOrigin]](idx)

def hts_idx_seqnames(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], n: UnsafePointer[c_int, MutExternalOrigin], getid: hts_id2name_f, hdr: MutOpaquePointer[MutExternalOrigin]) abi("C") -> UnsafePointer[UnsafePointer[c_char, ImmutExternalOrigin], MutExternalOrigin]:
    return external_call["hts_idx_seqnames", UnsafePointer[UnsafePointer[c_char, ImmutExternalOrigin], MutExternalOrigin], UnsafePointer[hts_idx_t, ImmutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin], hts_id2name_f, MutOpaquePointer[MutExternalOrigin]](idx, n, getid, hdr)

def hts_idx_nseq(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_idx_nseq", c_int, UnsafePointer[hts_idx_t, ImmutExternalOrigin]](idx)

def hts_parse_decimal(str: UnsafePointer[c_char, ImmutExternalOrigin], strend: UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], flags: c_int) abi("C") -> c_long_long:
    return external_call["hts_parse_decimal", c_long_long, UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], c_int](str, strend, flags)

def hts_parse_reg64(str: UnsafePointer[c_char, ImmutExternalOrigin], beg: UnsafePointer[hts_pos_t, MutExternalOrigin], end: UnsafePointer[hts_pos_t, MutExternalOrigin]) abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["hts_parse_reg64", UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[hts_pos_t, MutExternalOrigin], UnsafePointer[hts_pos_t, MutExternalOrigin]](str, beg, end)

def hts_parse_reg(str: UnsafePointer[c_char, ImmutExternalOrigin], beg: UnsafePointer[c_int, MutExternalOrigin], end: UnsafePointer[c_int, MutExternalOrigin]) abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["hts_parse_reg", UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin]](str, beg, end)

def hts_parse_region(s: UnsafePointer[c_char, ImmutExternalOrigin], tid: UnsafePointer[c_int, MutExternalOrigin], beg: UnsafePointer[hts_pos_t, MutExternalOrigin], end: UnsafePointer[hts_pos_t, MutExternalOrigin], getid: hts_name2id_f, hdr: MutOpaquePointer[MutExternalOrigin], flags: c_int) abi("C") -> UnsafePointer[c_char, ImmutExternalOrigin]:
    return external_call["hts_parse_region", UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin], UnsafePointer[hts_pos_t, MutExternalOrigin], UnsafePointer[hts_pos_t, MutExternalOrigin], hts_name2id_f, MutOpaquePointer[MutExternalOrigin], c_int](s, tid, beg, end, getid, hdr, flags)

def hts_itr_query(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], tid: c_int, beg: hts_pos_t, end: hts_pos_t, readrec: hts_itr_query_readrec_cb) abi("C") -> UnsafePointer[hts_itr_t, MutExternalOrigin]:
    return external_call["hts_itr_query", UnsafePointer[hts_itr_t, MutExternalOrigin], UnsafePointer[hts_idx_t, ImmutExternalOrigin], c_int, hts_pos_t, hts_pos_t, hts_itr_query_readrec_cb](idx, tid, beg, end, readrec)

def hts_itr_destroy(iter: UnsafePointer[hts_itr_t, MutExternalOrigin]) abi("C") -> None:
    external_call["hts_itr_destroy", NoneType, UnsafePointer[hts_itr_t, MutExternalOrigin]](iter)

def hts_itr_querys(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], reg: UnsafePointer[c_char, ImmutExternalOrigin], getid: hts_name2id_f, hdr: MutOpaquePointer[MutExternalOrigin], itr_query: hts_itr_querys_itr_query_cb, readrec: hts_itr_querys_readrec_cb) abi("C") -> UnsafePointer[hts_itr_t, MutExternalOrigin]:
    return external_call["hts_itr_querys", UnsafePointer[hts_itr_t, MutExternalOrigin], UnsafePointer[hts_idx_t, ImmutExternalOrigin], UnsafePointer[c_char, ImmutExternalOrigin], hts_name2id_f, MutOpaquePointer[MutExternalOrigin], hts_itr_querys_itr_query_cb, hts_itr_querys_readrec_cb](idx, reg, getid, hdr, itr_query, readrec)

def hts_itr_next(fp: UnsafePointer[BGZF, MutExternalOrigin], iter: UnsafePointer[hts_itr_t, MutExternalOrigin], r: MutOpaquePointer[MutExternalOrigin], data: MutOpaquePointer[MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_itr_next", c_int, UnsafePointer[BGZF, MutExternalOrigin], UnsafePointer[hts_itr_t, MutExternalOrigin], MutOpaquePointer[MutExternalOrigin], MutOpaquePointer[MutExternalOrigin]](fp, iter, r, data)

def hts_itr_multi_bam(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], iter: UnsafePointer[hts_itr_t, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_itr_multi_bam", c_int, UnsafePointer[hts_idx_t, ImmutExternalOrigin], UnsafePointer[hts_itr_t, MutExternalOrigin]](idx, iter)

def hts_itr_multi_cram(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], iter: UnsafePointer[hts_itr_t, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_itr_multi_cram", c_int, UnsafePointer[hts_idx_t, ImmutExternalOrigin], UnsafePointer[hts_itr_t, MutExternalOrigin]](idx, iter)

def hts_itr_regions(idx: UnsafePointer[hts_idx_t, ImmutExternalOrigin], reglist: UnsafePointer[hts_reglist_t, MutExternalOrigin], count: c_int, getid: hts_name2id_f, hdr: MutOpaquePointer[MutExternalOrigin], itr_specific: hts_itr_regions_itr_specific_cb, readrec: hts_itr_regions_readrec_cb, seek: hts_itr_regions_seek_cb, tell: hts_itr_regions_tell_cb) abi("C") -> UnsafePointer[hts_itr_t, MutExternalOrigin]:
    return external_call["hts_itr_regions", UnsafePointer[hts_itr_t, MutExternalOrigin], UnsafePointer[hts_idx_t, ImmutExternalOrigin], UnsafePointer[hts_reglist_t, MutExternalOrigin], c_int, hts_name2id_f, MutOpaquePointer[MutExternalOrigin], hts_itr_regions_itr_specific_cb, hts_itr_regions_readrec_cb, hts_itr_regions_seek_cb, hts_itr_regions_tell_cb](idx, reglist, count, getid, hdr, itr_specific, readrec, seek, tell)

def hts_itr_multi_next(fd: UnsafePointer[htsFile, MutExternalOrigin], iter: UnsafePointer[hts_itr_t, MutExternalOrigin], r: MutOpaquePointer[MutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_itr_multi_next", c_int, UnsafePointer[htsFile, MutExternalOrigin], UnsafePointer[hts_itr_t, MutExternalOrigin], MutOpaquePointer[MutExternalOrigin]](fd, iter, r)

def hts_reglist_create(argv: UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], argc: c_int, r_count: UnsafePointer[c_int, MutExternalOrigin], hdr: MutOpaquePointer[MutExternalOrigin], getid: hts_name2id_f) abi("C") -> UnsafePointer[hts_reglist_t, MutExternalOrigin]:
    return external_call["hts_reglist_create", UnsafePointer[hts_reglist_t, MutExternalOrigin], UnsafePointer[UnsafePointer[c_char, MutExternalOrigin], MutExternalOrigin], c_int, UnsafePointer[c_int, MutExternalOrigin], MutOpaquePointer[MutExternalOrigin], hts_name2id_f](argv, argc, r_count, hdr, getid)

def hts_reglist_free(reglist: UnsafePointer[hts_reglist_t, MutExternalOrigin], count: c_int) abi("C") -> None:
    external_call["hts_reglist_free", NoneType, UnsafePointer[hts_reglist_t, MutExternalOrigin], c_int](reglist, count)

def hts_file_type(fname: UnsafePointer[c_char, ImmutExternalOrigin]) abi("C") -> c_int:
    return external_call["hts_file_type", c_int, UnsafePointer[c_char, ImmutExternalOrigin]](fname)

def errmod_init(depcorr: c_double) abi("C") -> UnsafePointer[errmod_t, MutExternalOrigin]:
    return external_call["errmod_init", UnsafePointer[errmod_t, MutExternalOrigin], c_double](depcorr)

def errmod_destroy(em: UnsafePointer[errmod_t, MutExternalOrigin]) abi("C") -> None:
    external_call["errmod_destroy", NoneType, UnsafePointer[errmod_t, MutExternalOrigin]](em)

def errmod_cal(em: UnsafePointer[errmod_t, ImmutExternalOrigin], n: c_int, m: c_int, bases: UnsafePointer[uint16_t, MutExternalOrigin], q: UnsafePointer[c_float, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["errmod_cal", c_int, UnsafePointer[errmod_t, ImmutExternalOrigin], c_int, c_int, UnsafePointer[uint16_t, MutExternalOrigin], UnsafePointer[c_float, MutExternalOrigin]](em, n, m, bases, q)

def probaln_glocal(ref_: UnsafePointer[uint8_t, ImmutExternalOrigin], l_ref: c_int, query: UnsafePointer[uint8_t, ImmutExternalOrigin], l_query: c_int, iqual: UnsafePointer[uint8_t, ImmutExternalOrigin], c: UnsafePointer[probaln_par_t, ImmutExternalOrigin], state: UnsafePointer[c_int, MutExternalOrigin], q: UnsafePointer[uint8_t, MutExternalOrigin]) abi("C") -> c_int:
    return external_call["probaln_glocal", c_int, UnsafePointer[uint8_t, ImmutExternalOrigin], c_int, UnsafePointer[uint8_t, ImmutExternalOrigin], c_int, UnsafePointer[uint8_t, ImmutExternalOrigin], UnsafePointer[probaln_par_t, ImmutExternalOrigin], UnsafePointer[c_int, MutExternalOrigin], UnsafePointer[uint8_t, MutExternalOrigin]](ref_, l_ref, query, l_query, iqual, c, state, q)

def hts_md5_init() abi("C") -> UnsafePointer[hts_md5_context, MutExternalOrigin]:
    return external_call["hts_md5_init", UnsafePointer[hts_md5_context, MutExternalOrigin]]()

def hts_md5_update(ctx: UnsafePointer[hts_md5_context, MutExternalOrigin], data: ImmutOpaquePointer[ImmutExternalOrigin], size: c_ulong) abi("C") -> None:
    external_call["hts_md5_update", NoneType, UnsafePointer[hts_md5_context, MutExternalOrigin], ImmutOpaquePointer[ImmutExternalOrigin], c_ulong](ctx, data, size)

def hts_md5_final(digest: UnsafePointer[c_uchar, MutExternalOrigin], ctx: UnsafePointer[hts_md5_context, MutExternalOrigin]) abi("C") -> None:
    external_call["hts_md5_final", NoneType, UnsafePointer[c_uchar, MutExternalOrigin], UnsafePointer[hts_md5_context, MutExternalOrigin]](digest, ctx)

def hts_md5_reset(ctx: UnsafePointer[hts_md5_context, MutExternalOrigin]) abi("C") -> None:
    external_call["hts_md5_reset", NoneType, UnsafePointer[hts_md5_context, MutExternalOrigin]](ctx)

def hts_md5_hex(hex: UnsafePointer[c_char, MutExternalOrigin], digest: UnsafePointer[c_uchar, ImmutExternalOrigin]) abi("C") -> None:
    external_call["hts_md5_hex", NoneType, UnsafePointer[c_char, MutExternalOrigin], UnsafePointer[c_uchar, ImmutExternalOrigin]](hex, digest)

def hts_md5_destroy(ctx: UnsafePointer[hts_md5_context, MutExternalOrigin]) abi("C") -> None:
    external_call["hts_md5_destroy", NoneType, UnsafePointer[hts_md5_context, MutExternalOrigin]](ctx)

def hts_reg2bin(beg: hts_pos_t, end: hts_pos_t, min_shift: c_int, n_lvls: c_int) abi("C") -> c_int:
    return external_call["hts_reg2bin", c_int, hts_pos_t, hts_pos_t, c_int, c_int](beg, end, min_shift, n_lvls)

def hts_bin_level(bin: c_int) abi("C") -> c_int:
    return external_call["hts_bin_level", c_int, c_int](bin)

def hts_crc32(crc: uint32_t, buf: ImmutOpaquePointer[ImmutExternalOrigin], len: size_t) abi("C") -> uint32_t:
    return external_call["hts_crc32", uint32_t, uint32_t, ImmutOpaquePointer[ImmutExternalOrigin], size_t](crc, buf, len)

def hts_bin_bot(bin: c_int, n_lvls: c_int) abi("C") -> c_int:
    return external_call["hts_bin_bot", c_int, c_int, c_int](bin, n_lvls)

def hts_bin_maxpos(min_shift: c_int, n_lvls: c_int) abi("C") -> hts_pos_t:
    return external_call["hts_bin_maxpos", hts_pos_t, c_int, c_int](min_shift, n_lvls)

def ed_is_big() abi("C") -> c_int:
    return external_call["ed_is_big", c_int]()

def ed_swap_2(v: uint16_t) abi("C") -> uint16_t:
    return external_call["ed_swap_2", uint16_t, uint16_t](v)

def ed_swap_2p(x: MutOpaquePointer[MutExternalOrigin]) abi("C") -> MutOpaquePointer[MutExternalOrigin]:
    return external_call["ed_swap_2p", MutOpaquePointer[MutExternalOrigin], MutOpaquePointer[MutExternalOrigin]](x)

def ed_swap_4(v: uint32_t) abi("C") -> uint32_t:
    return external_call["ed_swap_4", uint32_t, uint32_t](v)

def ed_swap_4p(x: MutOpaquePointer[MutExternalOrigin]) abi("C") -> MutOpaquePointer[MutExternalOrigin]:
    return external_call["ed_swap_4p", MutOpaquePointer[MutExternalOrigin], MutOpaquePointer[MutExternalOrigin]](x)

def ed_swap_8(v: uint64_t) abi("C") -> uint64_t:
    return external_call["ed_swap_8", uint64_t, uint64_t](v)

def ed_swap_8p(x: MutOpaquePointer[MutExternalOrigin]) abi("C") -> MutOpaquePointer[MutExternalOrigin]:
    return external_call["ed_swap_8p", MutOpaquePointer[MutExternalOrigin], MutOpaquePointer[MutExternalOrigin]](x)
