# Generated by mojo_bindgen - do not edit by hand.
# layout tests for: _ffi_all

from std.sys.info import align_of, size_of
from std.reflection import reflect
from _ffi_all import htsFormat__anon_struct_1, htsFormat, htsFile, htsThreadPool, hts_opt, hts_pair_pos_t, hts_pair64_t, hts_pair64_max_t, hts_reglist_t, hts_itr_t__anon_struct_1, hts_itr_t, probaln_par_t, sam_hdr_t, bam1_core_t, bam1_t, bam_pileup1_t, hts_base_mod


def _check_eq(label: String, got: Int, expected: Int) raises:
    if got != expected:
        raise Error(label + ": got " + String(got) + ", expected " + String(expected))


def test_layout_htsFormat__anon_struct_1() raises:
    comptime r = reflect[htsFormat__anon_struct_1]()
    _check_eq("htsFormat__anon_struct_1.size", Int(size_of[htsFormat__anon_struct_1]()), 4)
    _check_eq("htsFormat__anon_struct_1.align", Int(align_of[htsFormat__anon_struct_1]()), 2)
    _check_eq("htsFormat__anon_struct_1.major.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("htsFormat__anon_struct_1.minor.offset", Int(r.field_offset[index=1]()), 2)


def test_layout_htsFormat() raises:
    comptime r = reflect[htsFormat]()
    _check_eq("htsFormat.size", Int(size_of[htsFormat]()), 32)
    _check_eq("htsFormat.align", Int(align_of[htsFormat]()), 8)
    _check_eq("htsFormat.category.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("htsFormat.format.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("htsFormat.version.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("htsFormat.compression.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("htsFormat.compression_level.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("htsFormat.specific.offset", Int(r.field_offset[index=5]()), 24)


# def test_layout_htsFile() raises:
#     comptime r = reflect[htsFile]()
#     # _check_eq("htsFile.size", Int(size_of[htsFile]()), 136)
#     # _check_eq("htsFile.align", Int(align_of[htsFile]()), 8)
#     _check_eq("htsFile.lineno.offset", Int(r.field_offset[index=0]()), 8)
#     _check_eq("htsFile.line.offset", Int(r.field_offset[index=1]()), 16)
#     _check_eq("htsFile.fn_.offset", Int(r.field_offset[index=2]()), 40)
#     _check_eq("htsFile.fn_aux.offset", Int(r.field_offset[index=3]()), 48)
#     _check_eq("htsFile.fp.offset", Int(r.field_offset[index=4]()), 56)
#     _check_eq("htsFile.state.offset", Int(r.field_offset[index=5]()), 64)
#     _check_eq("htsFile.format.offset", Int(r.field_offset[index=6]()), 72)
#     _check_eq("htsFile.idx.offset", Int(r.field_offset[index=7]()), 104)
#     _check_eq("htsFile.fnidx.offset", Int(r.field_offset[index=8]()), 112)
#     _check_eq("htsFile.bam_header.offset", Int(r.field_offset[index=9]()), 120)
#     _check_eq("htsFile.filter.offset", Int(r.field_offset[index=10]()), 128)


def test_layout_htsThreadPool() raises:
    comptime r = reflect[htsThreadPool]()
    _check_eq("htsThreadPool.size", Int(size_of[htsThreadPool]()), 16)
    _check_eq("htsThreadPool.align", Int(align_of[htsThreadPool]()), 8)
    _check_eq("htsThreadPool.pool.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("htsThreadPool.qsize.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_hts_opt() raises:
    comptime r = reflect[hts_opt]()
    _check_eq("hts_opt.size", Int(size_of[hts_opt]()), 32)
    _check_eq("hts_opt.align", Int(align_of[hts_opt]()), 8)
    _check_eq("hts_opt.arg.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_opt.opt.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hts_opt.val.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("hts_opt.next.offset", Int(r.field_offset[index=3]()), 24)


def test_layout_hts_pair_pos_t() raises:
    comptime r = reflect[hts_pair_pos_t]()
    _check_eq("hts_pair_pos_t.size", Int(size_of[hts_pair_pos_t]()), 16)
    _check_eq("hts_pair_pos_t.align", Int(align_of[hts_pair_pos_t]()), 8)
    _check_eq("hts_pair_pos_t.beg.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_pair_pos_t.end.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_hts_pair64_t() raises:
    comptime r = reflect[hts_pair64_t]()
    _check_eq("hts_pair64_t.size", Int(size_of[hts_pair64_t]()), 16)
    _check_eq("hts_pair64_t.align", Int(align_of[hts_pair64_t]()), 8)
    _check_eq("hts_pair64_t.u.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_pair64_t.v.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_hts_pair64_max_t() raises:
    comptime r = reflect[hts_pair64_max_t]()
    _check_eq("hts_pair64_max_t.size", Int(size_of[hts_pair64_max_t]()), 24)
    _check_eq("hts_pair64_max_t.align", Int(align_of[hts_pair64_max_t]()), 8)
    _check_eq("hts_pair64_max_t.u.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_pair64_max_t.v.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hts_pair64_max_t.max.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_hts_reglist_t() raises:
    comptime r = reflect[hts_reglist_t]()
    _check_eq("hts_reglist_t.size", Int(size_of[hts_reglist_t]()), 40)
    _check_eq("hts_reglist_t.align", Int(align_of[hts_reglist_t]()), 8)
    _check_eq("hts_reglist_t.reg.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_reglist_t.intervals.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hts_reglist_t.tid.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("hts_reglist_t.count.offset", Int(r.field_offset[index=3]()), 20)
    _check_eq("hts_reglist_t.min_beg.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("hts_reglist_t.max_end.offset", Int(r.field_offset[index=5]()), 32)


def test_layout_hts_itr_t__anon_struct_1() raises:
    comptime r = reflect[hts_itr_t__anon_struct_1]()
    _check_eq("hts_itr_t__anon_struct_1.size", Int(size_of[hts_itr_t__anon_struct_1]()), 16)
    _check_eq("hts_itr_t__anon_struct_1.align", Int(align_of[hts_itr_t__anon_struct_1]()), 8)
    _check_eq("hts_itr_t__anon_struct_1.n.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_itr_t__anon_struct_1.m.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("hts_itr_t__anon_struct_1.a.offset", Int(r.field_offset[index=2]()), 8)


def test_layout_hts_itr_t() raises:
    comptime r = reflect[hts_itr_t]()
    _check_eq("hts_itr_t.size", Int(size_of[hts_itr_t]()), 144)
    _check_eq("hts_itr_t.align", Int(align_of[hts_itr_t]()), 8)
    _check_eq("hts_itr_t.tid.offset", Int(r.field_offset[index=0]()), 4)
    _check_eq("hts_itr_t.n_off.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hts_itr_t.i.offset", Int(r.field_offset[index=2]()), 12)
    _check_eq("hts_itr_t.n_reg.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("hts_itr_t.beg.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("hts_itr_t.end.offset", Int(r.field_offset[index=5]()), 32)
    _check_eq("hts_itr_t.reg_list.offset", Int(r.field_offset[index=6]()), 40)
    _check_eq("hts_itr_t.curr_tid.offset", Int(r.field_offset[index=7]()), 48)
    _check_eq("hts_itr_t.curr_reg.offset", Int(r.field_offset[index=8]()), 52)
    _check_eq("hts_itr_t.curr_intv.offset", Int(r.field_offset[index=9]()), 56)
    _check_eq("hts_itr_t.curr_beg.offset", Int(r.field_offset[index=10]()), 64)
    _check_eq("hts_itr_t.curr_end.offset", Int(r.field_offset[index=11]()), 72)
    _check_eq("hts_itr_t.curr_off.offset", Int(r.field_offset[index=12]()), 80)
    _check_eq("hts_itr_t.nocoor_off.offset", Int(r.field_offset[index=13]()), 88)
    _check_eq("hts_itr_t.off.offset", Int(r.field_offset[index=14]()), 96)
    _check_eq("hts_itr_t.readrec.offset", Int(r.field_offset[index=15]()), 104)
    _check_eq("hts_itr_t.seek.offset", Int(r.field_offset[index=16]()), 112)
    _check_eq("hts_itr_t.tell.offset", Int(r.field_offset[index=17]()), 120)
    _check_eq("hts_itr_t.bins.offset", Int(r.field_offset[index=18]()), 128)


def test_layout_probaln_par_t() raises:
    comptime r = reflect[probaln_par_t]()
    _check_eq("probaln_par_t.size", Int(size_of[probaln_par_t]()), 12)
    _check_eq("probaln_par_t.align", Int(align_of[probaln_par_t]()), 4)
    _check_eq("probaln_par_t.d.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("probaln_par_t.e.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("probaln_par_t.bw.offset", Int(r.field_offset[index=2]()), 8)


def test_layout_sam_hdr_t() raises:
    comptime r = reflect[sam_hdr_t]()
    _check_eq("sam_hdr_t.size", Int(size_of[sam_hdr_t]()), 72)
    _check_eq("sam_hdr_t.align", Int(align_of[sam_hdr_t]()), 8)
    _check_eq("sam_hdr_t.n_targets.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("sam_hdr_t.ignore_sam_err.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("sam_hdr_t.l_text.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("sam_hdr_t.target_len.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("sam_hdr_t.cigar_tab.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("sam_hdr_t.target_name.offset", Int(r.field_offset[index=5]()), 32)
    _check_eq("sam_hdr_t.text.offset", Int(r.field_offset[index=6]()), 40)
    _check_eq("sam_hdr_t.sdict.offset", Int(r.field_offset[index=7]()), 48)
    _check_eq("sam_hdr_t.hrecs.offset", Int(r.field_offset[index=8]()), 56)
    _check_eq("sam_hdr_t.ref_count.offset", Int(r.field_offset[index=9]()), 64)


def test_layout_bam1_core_t() raises:
    comptime r = reflect[bam1_core_t]()
    _check_eq("bam1_core_t.size", Int(size_of[bam1_core_t]()), 48)
    _check_eq("bam1_core_t.align", Int(align_of[bam1_core_t]()), 8)
    _check_eq("bam1_core_t.pos.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bam1_core_t.tid.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bam1_core_t.bin.offset", Int(r.field_offset[index=2]()), 12)
    _check_eq("bam1_core_t.qual.offset", Int(r.field_offset[index=3]()), 14)
    _check_eq("bam1_core_t.l_extranul.offset", Int(r.field_offset[index=4]()), 15)
    _check_eq("bam1_core_t.flag.offset", Int(r.field_offset[index=5]()), 16)
    _check_eq("bam1_core_t.l_qname.offset", Int(r.field_offset[index=6]()), 18)
    _check_eq("bam1_core_t.n_cigar.offset", Int(r.field_offset[index=7]()), 20)
    _check_eq("bam1_core_t.l_qseq.offset", Int(r.field_offset[index=8]()), 24)
    _check_eq("bam1_core_t.mtid.offset", Int(r.field_offset[index=9]()), 28)
    _check_eq("bam1_core_t.mpos.offset", Int(r.field_offset[index=10]()), 32)
    _check_eq("bam1_core_t.isize.offset", Int(r.field_offset[index=11]()), 40)


def test_layout_bam1_t() raises:
    comptime r = reflect[bam1_t]()
    _check_eq("bam1_t.size", Int(size_of[bam1_t]()), 80)
    _check_eq("bam1_t.align", Int(align_of[bam1_t]()), 8)
    _check_eq("bam1_t.core.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bam1_t.id.offset", Int(r.field_offset[index=1]()), 48)
    _check_eq("bam1_t.data.offset", Int(r.field_offset[index=2]()), 56)
    _check_eq("bam1_t.l_data.offset", Int(r.field_offset[index=3]()), 64)
    _check_eq("bam1_t.m_data.offset", Int(r.field_offset[index=4]()), 68)


def test_layout_bam_pileup1_t() raises:
    comptime r = reflect[bam_pileup1_t]()
    _check_eq("bam_pileup1_t.size", Int(size_of[bam_pileup1_t]()), 40)
    _check_eq("bam_pileup1_t.align", Int(align_of[bam_pileup1_t]()), 8)
    _check_eq("bam_pileup1_t.b.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bam_pileup1_t.qpos.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bam_pileup1_t.indel.offset", Int(r.field_offset[index=2]()), 12)
    _check_eq("bam_pileup1_t.level.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("bam_pileup1_t.cd.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("bam_pileup1_t.cigar_ind.offset", Int(r.field_offset[index=5]()), 32)


def test_layout_hts_base_mod() raises:
    comptime r = reflect[hts_base_mod]()
    _check_eq("hts_base_mod.size", Int(size_of[hts_base_mod]()), 16)
    _check_eq("hts_base_mod.align", Int(align_of[hts_base_mod]()), 4)
    _check_eq("hts_base_mod.modified_base.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_base_mod.canonical_base.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("hts_base_mod.strand.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("hts_base_mod.qual.offset", Int(r.field_offset[index=3]()), 12)


def main() raises:
    test_layout_htsFormat__anon_struct_1()
    test_layout_htsFormat()
    # test_layout_htsFile()
    test_layout_htsThreadPool()
    test_layout_hts_opt()
    test_layout_hts_pair_pos_t()
    test_layout_hts_pair64_t()
    test_layout_hts_pair64_max_t()
    test_layout_hts_reglist_t()
    test_layout_hts_itr_t__anon_struct_1()
    # test_layout_hts_itr_t()
    test_layout_probaln_par_t()
    test_layout_sam_hdr_t()
    test_layout_bam1_core_t()
    test_layout_bam1_t()
    test_layout_bam_pileup1_t()
    test_layout_hts_base_mod()
