[workspace]
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda", "https://conda.modular.com/max-nightly/"]
name = "hts_mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
mojo = "*"
htslib = { channel = "bioconda" }
