# Generated by mojo_bindgen - do not edit by hand.
# layout tests for: _ffi.mojo

from std.testing import TestSuite
from std.sys.info import align_of, size_of
from std.reflection import reflect
from _ffi.mojo import max_align_t, __fsid_t, imaxdiv_t, div_t, ldiv_t, lldiv_t, __sigset_t, timeval, timespec, fd_set, atomic_wide_counter__anon_struct_1, __pthread_internal_list, __pthread_internal_slist, __pthread_mutex_s, __pthread_rwlock_arch_t, __pthread_cond_s, __once_flag, random_data, drand48_data, __locale_struct, __mbstate_t, _G_fpos_t, _G_fpos64_t, _IO_FILE, _IO_cookie_io_functions_t, kstring_t, ks_tokaux_t, htsFormat__anon_struct_1, htsFormat, htsFile, htsThreadPool, hts_opt, hts_pair_pos_t, hts_pair64_t, hts_pair64_max_t, hts_reglist_t, hts_itr_t__anon_struct_1, hts_itr_t, probaln_par_t, bcf_hrec_t, bcf_idinfo_t, bcf_idpair_t, bcf_hdr_t, bcf_variant_t, bcf_fmt_t, bcf_info_t, bcf_dec_t, bcf1_t, sam_hdr_t, bam1_core_t, bam1_t, bam_pileup1_t, hts_base_mod, hFILE, cram_method_details, BGZF, tbx_conf_t, tbx_t, bcf_sr_regions_t, bcf_sr_t, bcf_srs_t, kbitset_t, kbitset_iter_t


def _check_eq(label: String, got: Int, expected: Int) raises:
    if got != expected:
        raise Error(label + ": got " + String(got) + ", expected " + String(expected))


def test_layout_max_align_t() raises:
    comptime r = reflect[max_align_t]
    _check_eq("max_align_t.size", Int(size_of[max_align_t]()), 32)
    _check_eq("max_align_t.align", Int(align_of[max_align_t]()), 16)
    _check_eq("max_align_t.__max_align_ll.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("max_align_t.__max_align_ld.offset", Int(r.field_offset[index=1]()), 16)


def test_layout___fsid_t() raises:
    comptime r = reflect[__fsid_t]
    _check_eq("__fsid_t.size", Int(size_of[__fsid_t]()), 8)
    _check_eq("__fsid_t.align", Int(align_of[__fsid_t]()), 4)
    _check_eq("__fsid_t.__val.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_imaxdiv_t() raises:
    comptime r = reflect[imaxdiv_t]
    _check_eq("imaxdiv_t.size", Int(size_of[imaxdiv_t]()), 16)
    _check_eq("imaxdiv_t.align", Int(align_of[imaxdiv_t]()), 8)
    _check_eq("imaxdiv_t.quot.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("imaxdiv_t.rem.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_div_t() raises:
    comptime r = reflect[div_t]
    _check_eq("div_t.size", Int(size_of[div_t]()), 8)
    _check_eq("div_t.align", Int(align_of[div_t]()), 4)
    _check_eq("div_t.quot.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("div_t.rem.offset", Int(r.field_offset[index=1]()), 4)


def test_layout_ldiv_t() raises:
    comptime r = reflect[ldiv_t]
    _check_eq("ldiv_t.size", Int(size_of[ldiv_t]()), 16)
    _check_eq("ldiv_t.align", Int(align_of[ldiv_t]()), 8)
    _check_eq("ldiv_t.quot.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("ldiv_t.rem.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_lldiv_t() raises:
    comptime r = reflect[lldiv_t]
    _check_eq("lldiv_t.size", Int(size_of[lldiv_t]()), 16)
    _check_eq("lldiv_t.align", Int(align_of[lldiv_t]()), 8)
    _check_eq("lldiv_t.quot.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("lldiv_t.rem.offset", Int(r.field_offset[index=1]()), 8)


def test_layout___sigset_t() raises:
    comptime r = reflect[__sigset_t]
    _check_eq("__sigset_t.size", Int(size_of[__sigset_t]()), 128)
    _check_eq("__sigset_t.align", Int(align_of[__sigset_t]()), 8)
    _check_eq("__sigset_t.__val.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_timeval() raises:
    comptime r = reflect[timeval]
    _check_eq("timeval.size", Int(size_of[timeval]()), 16)
    _check_eq("timeval.align", Int(align_of[timeval]()), 8)
    _check_eq("timeval.tv_sec.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("timeval.tv_usec.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_timespec() raises:
    comptime r = reflect[timespec]
    _check_eq("timespec.size", Int(size_of[timespec]()), 16)
    _check_eq("timespec.align", Int(align_of[timespec]()), 8)
    _check_eq("timespec.tv_sec.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("timespec.tv_nsec.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_fd_set() raises:
    comptime r = reflect[fd_set]
    _check_eq("fd_set.size", Int(size_of[fd_set]()), 128)
    _check_eq("fd_set.align", Int(align_of[fd_set]()), 8)
    _check_eq("fd_set.__fds_bits.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_atomic_wide_counter__anon_struct_1() raises:
    comptime r = reflect[atomic_wide_counter__anon_struct_1]
    _check_eq("atomic_wide_counter__anon_struct_1.size", Int(size_of[atomic_wide_counter__anon_struct_1]()), 8)
    _check_eq("atomic_wide_counter__anon_struct_1.align", Int(align_of[atomic_wide_counter__anon_struct_1]()), 4)
    _check_eq("atomic_wide_counter__anon_struct_1.__low.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("atomic_wide_counter__anon_struct_1.__high.offset", Int(r.field_offset[index=1]()), 4)


def test_layout___pthread_internal_list() raises:
    comptime r = reflect[__pthread_internal_list]
    _check_eq("__pthread_internal_list.size", Int(size_of[__pthread_internal_list]()), 16)
    _check_eq("__pthread_internal_list.align", Int(align_of[__pthread_internal_list]()), 8)
    _check_eq("__pthread_internal_list.__prev.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("__pthread_internal_list.__next.offset", Int(r.field_offset[index=1]()), 8)


def test_layout___pthread_internal_slist() raises:
    comptime r = reflect[__pthread_internal_slist]
    _check_eq("__pthread_internal_slist.size", Int(size_of[__pthread_internal_slist]()), 8)
    _check_eq("__pthread_internal_slist.align", Int(align_of[__pthread_internal_slist]()), 8)
    _check_eq("__pthread_internal_slist.__next.offset", Int(r.field_offset[index=0]()), 0)


def test_layout___pthread_mutex_s() raises:
    comptime r = reflect[__pthread_mutex_s]
    _check_eq("__pthread_mutex_s.size", Int(size_of[__pthread_mutex_s]()), 40)
    _check_eq("__pthread_mutex_s.align", Int(align_of[__pthread_mutex_s]()), 8)
    _check_eq("__pthread_mutex_s.__lock.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("__pthread_mutex_s.__count.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("__pthread_mutex_s.__owner.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("__pthread_mutex_s.__nusers.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("__pthread_mutex_s.__kind.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("__pthread_mutex_s.__spins.offset", Int(r.field_offset[index=5]()), 20)
    _check_eq("__pthread_mutex_s.__elision.offset", Int(r.field_offset[index=6]()), 22)
    _check_eq("__pthread_mutex_s.__list.offset", Int(r.field_offset[index=7]()), 24)


def test_layout___pthread_rwlock_arch_t() raises:
    comptime r = reflect[__pthread_rwlock_arch_t]
    _check_eq("__pthread_rwlock_arch_t.size", Int(size_of[__pthread_rwlock_arch_t]()), 56)
    _check_eq("__pthread_rwlock_arch_t.align", Int(align_of[__pthread_rwlock_arch_t]()), 8)
    _check_eq("__pthread_rwlock_arch_t.__readers.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("__pthread_rwlock_arch_t.__writers.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("__pthread_rwlock_arch_t.__wrphase_futex.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("__pthread_rwlock_arch_t.__writers_futex.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("__pthread_rwlock_arch_t.__pad3.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("__pthread_rwlock_arch_t.__pad4.offset", Int(r.field_offset[index=5]()), 20)
    _check_eq("__pthread_rwlock_arch_t.__cur_writer.offset", Int(r.field_offset[index=6]()), 24)
    _check_eq("__pthread_rwlock_arch_t.__shared.offset", Int(r.field_offset[index=7]()), 28)
    _check_eq("__pthread_rwlock_arch_t.__rwelision.offset", Int(r.field_offset[index=8]()), 32)
    _check_eq("__pthread_rwlock_arch_t.__pad1.offset", Int(r.field_offset[index=9]()), 33)
    _check_eq("__pthread_rwlock_arch_t.__pad2.offset", Int(r.field_offset[index=10]()), 40)
    _check_eq("__pthread_rwlock_arch_t.__flags.offset", Int(r.field_offset[index=11]()), 48)


def test_layout___pthread_cond_s() raises:
    comptime r = reflect[__pthread_cond_s]
    _check_eq("__pthread_cond_s.size", Int(size_of[__pthread_cond_s]()), 48)
    _check_eq("__pthread_cond_s.align", Int(align_of[__pthread_cond_s]()), 8)
    _check_eq("__pthread_cond_s.__wseq.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("__pthread_cond_s.__g1_start.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("__pthread_cond_s.__g_refs.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("__pthread_cond_s.__g_size.offset", Int(r.field_offset[index=3]()), 24)
    _check_eq("__pthread_cond_s.__g1_orig_size.offset", Int(r.field_offset[index=4]()), 32)
    _check_eq("__pthread_cond_s.__wrefs.offset", Int(r.field_offset[index=5]()), 36)
    _check_eq("__pthread_cond_s.__g_signals.offset", Int(r.field_offset[index=6]()), 40)


def test_layout___once_flag() raises:
    comptime r = reflect[__once_flag]
    _check_eq("__once_flag.size", Int(size_of[__once_flag]()), 4)
    _check_eq("__once_flag.align", Int(align_of[__once_flag]()), 4)
    _check_eq("__once_flag.__data.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_random_data() raises:
    comptime r = reflect[random_data]
    _check_eq("random_data.size", Int(size_of[random_data]()), 48)
    _check_eq("random_data.align", Int(align_of[random_data]()), 8)
    _check_eq("random_data.fptr.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("random_data.rptr.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("random_data.state.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("random_data.rand_type.offset", Int(r.field_offset[index=3]()), 24)
    _check_eq("random_data.rand_deg.offset", Int(r.field_offset[index=4]()), 28)
    _check_eq("random_data.rand_sep.offset", Int(r.field_offset[index=5]()), 32)
    _check_eq("random_data.end_ptr.offset", Int(r.field_offset[index=6]()), 40)


def test_layout_drand48_data() raises:
    comptime r = reflect[drand48_data]
    _check_eq("drand48_data.size", Int(size_of[drand48_data]()), 24)
    _check_eq("drand48_data.align", Int(align_of[drand48_data]()), 8)
    _check_eq("drand48_data.__x.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("drand48_data.__old_x.offset", Int(r.field_offset[index=1]()), 6)
    _check_eq("drand48_data.__c.offset", Int(r.field_offset[index=2]()), 12)
    _check_eq("drand48_data.__init.offset", Int(r.field_offset[index=3]()), 14)
    _check_eq("drand48_data.__a.offset", Int(r.field_offset[index=4]()), 16)


def test_layout___locale_struct() raises:
    comptime r = reflect[__locale_struct]
    _check_eq("__locale_struct.size", Int(size_of[__locale_struct]()), 232)
    _check_eq("__locale_struct.align", Int(align_of[__locale_struct]()), 8)
    _check_eq("__locale_struct.__locales.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("__locale_struct.__ctype_b.offset", Int(r.field_offset[index=1]()), 104)
    _check_eq("__locale_struct.__ctype_tolower.offset", Int(r.field_offset[index=2]()), 112)
    _check_eq("__locale_struct.__ctype_toupper.offset", Int(r.field_offset[index=3]()), 120)
    _check_eq("__locale_struct.__names.offset", Int(r.field_offset[index=4]()), 128)


def test_layout___mbstate_t() raises:
    comptime r = reflect[__mbstate_t]
    _check_eq("__mbstate_t.size", Int(size_of[__mbstate_t]()), 8)
    _check_eq("__mbstate_t.align", Int(align_of[__mbstate_t]()), 4)
    _check_eq("__mbstate_t.__count.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("__mbstate_t.__value.offset", Int(r.field_offset[index=1]()), 4)


def test_layout__G_fpos_t() raises:
    comptime r = reflect[_G_fpos_t]
    _check_eq("_G_fpos_t.size", Int(size_of[_G_fpos_t]()), 16)
    _check_eq("_G_fpos_t.align", Int(align_of[_G_fpos_t]()), 8)
    _check_eq("_G_fpos_t.__pos.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("_G_fpos_t.__state.offset", Int(r.field_offset[index=1]()), 8)


def test_layout__G_fpos64_t() raises:
    comptime r = reflect[_G_fpos64_t]
    _check_eq("_G_fpos64_t.size", Int(size_of[_G_fpos64_t]()), 16)
    _check_eq("_G_fpos64_t.align", Int(align_of[_G_fpos64_t]()), 8)
    _check_eq("_G_fpos64_t.__pos.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("_G_fpos64_t.__state.offset", Int(r.field_offset[index=1]()), 8)


def test_layout__IO_FILE() raises:
    comptime r = reflect[_IO_FILE]
    _check_eq("_IO_FILE.size", Int(size_of[_IO_FILE]()), 216)
    _check_eq("_IO_FILE.align", Int(align_of[_IO_FILE]()), 8)
    _check_eq("_IO_FILE._flags.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("_IO_FILE._IO_read_ptr.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("_IO_FILE._IO_read_end.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("_IO_FILE._IO_read_base.offset", Int(r.field_offset[index=3]()), 24)
    _check_eq("_IO_FILE._IO_write_base.offset", Int(r.field_offset[index=4]()), 32)
    _check_eq("_IO_FILE._IO_write_ptr.offset", Int(r.field_offset[index=5]()), 40)
    _check_eq("_IO_FILE._IO_write_end.offset", Int(r.field_offset[index=6]()), 48)
    _check_eq("_IO_FILE._IO_buf_base.offset", Int(r.field_offset[index=7]()), 56)
    _check_eq("_IO_FILE._IO_buf_end.offset", Int(r.field_offset[index=8]()), 64)
    _check_eq("_IO_FILE._IO_save_base.offset", Int(r.field_offset[index=9]()), 72)
    _check_eq("_IO_FILE._IO_backup_base.offset", Int(r.field_offset[index=10]()), 80)
    _check_eq("_IO_FILE._IO_save_end.offset", Int(r.field_offset[index=11]()), 88)
    _check_eq("_IO_FILE._markers.offset", Int(r.field_offset[index=12]()), 96)
    _check_eq("_IO_FILE._chain.offset", Int(r.field_offset[index=13]()), 104)
    _check_eq("_IO_FILE._fileno.offset", Int(r.field_offset[index=14]()), 112)
    _check_eq("_IO_FILE._flags2.offset", Int(r.field_offset[index=15]()), 116)
    _check_eq("_IO_FILE._old_offset.offset", Int(r.field_offset[index=16]()), 120)
    _check_eq("_IO_FILE._cur_column.offset", Int(r.field_offset[index=17]()), 128)
    _check_eq("_IO_FILE._vtable_offset.offset", Int(r.field_offset[index=18]()), 130)
    _check_eq("_IO_FILE._shortbuf.offset", Int(r.field_offset[index=19]()), 131)
    _check_eq("_IO_FILE._lock.offset", Int(r.field_offset[index=20]()), 136)
    _check_eq("_IO_FILE._offset.offset", Int(r.field_offset[index=21]()), 144)
    _check_eq("_IO_FILE._codecvt.offset", Int(r.field_offset[index=22]()), 152)
    _check_eq("_IO_FILE._wide_data.offset", Int(r.field_offset[index=23]()), 160)
    _check_eq("_IO_FILE._freeres_list.offset", Int(r.field_offset[index=24]()), 168)
    _check_eq("_IO_FILE._freeres_buf.offset", Int(r.field_offset[index=25]()), 176)
    _check_eq("_IO_FILE.__pad5.offset", Int(r.field_offset[index=26]()), 184)
    _check_eq("_IO_FILE._mode.offset", Int(r.field_offset[index=27]()), 192)
    _check_eq("_IO_FILE._unused2.offset", Int(r.field_offset[index=28]()), 196)


def test_layout__IO_cookie_io_functions_t() raises:
    comptime r = reflect[_IO_cookie_io_functions_t]
    _check_eq("_IO_cookie_io_functions_t.size", Int(size_of[_IO_cookie_io_functions_t]()), 32)
    _check_eq("_IO_cookie_io_functions_t.align", Int(align_of[_IO_cookie_io_functions_t]()), 8)
    _check_eq("_IO_cookie_io_functions_t.read.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("_IO_cookie_io_functions_t.write.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("_IO_cookie_io_functions_t.seek.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("_IO_cookie_io_functions_t.close.offset", Int(r.field_offset[index=3]()), 24)


def test_layout_kstring_t() raises:
    comptime r = reflect[kstring_t]
    _check_eq("kstring_t.size", Int(size_of[kstring_t]()), 24)
    _check_eq("kstring_t.align", Int(align_of[kstring_t]()), 8)
    _check_eq("kstring_t.l.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("kstring_t.m.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("kstring_t.s.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_ks_tokaux_t() raises:
    comptime r = reflect[ks_tokaux_t]
    _check_eq("ks_tokaux_t.size", Int(size_of[ks_tokaux_t]()), 48)
    _check_eq("ks_tokaux_t.align", Int(align_of[ks_tokaux_t]()), 8)
    _check_eq("ks_tokaux_t.tab.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("ks_tokaux_t.sep.offset", Int(r.field_offset[index=1]()), 32)
    _check_eq("ks_tokaux_t.finished.offset", Int(r.field_offset[index=2]()), 36)
    _check_eq("ks_tokaux_t.p.offset", Int(r.field_offset[index=3]()), 40)


def test_layout_htsFormat__anon_struct_1() raises:
    comptime r = reflect[htsFormat__anon_struct_1]
    _check_eq("htsFormat__anon_struct_1.size", Int(size_of[htsFormat__anon_struct_1]()), 4)
    _check_eq("htsFormat__anon_struct_1.align", Int(align_of[htsFormat__anon_struct_1]()), 2)
    _check_eq("htsFormat__anon_struct_1.major.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("htsFormat__anon_struct_1.minor.offset", Int(r.field_offset[index=1]()), 2)


def test_layout_htsFormat() raises:
    comptime r = reflect[htsFormat]
    _check_eq("htsFormat.size", Int(size_of[htsFormat]()), 32)
    _check_eq("htsFormat.align", Int(align_of[htsFormat]()), 8)
    _check_eq("htsFormat.category.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("htsFormat.format.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("htsFormat.version.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("htsFormat.compression.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("htsFormat.compression_level.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("htsFormat.specific.offset", Int(r.field_offset[index=5]()), 24)


def test_layout_htsFile() raises:
    comptime r = reflect[htsFile]
    _check_eq("htsFile.size", Int(size_of[htsFile]()), 136)
    _check_eq("htsFile.align", Int(align_of[htsFile]()), 8)
    _check_eq("htsFile.lineno.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("htsFile.line.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("htsFile.fn_.offset", Int(r.field_offset[index=3]()), 40)
    _check_eq("htsFile.fn_aux.offset", Int(r.field_offset[index=4]()), 48)
    _check_eq("htsFile.fp.offset", Int(r.field_offset[index=5]()), 56)
    _check_eq("htsFile.state.offset", Int(r.field_offset[index=6]()), 64)
    _check_eq("htsFile.format.offset", Int(r.field_offset[index=7]()), 72)
    _check_eq("htsFile.idx.offset", Int(r.field_offset[index=8]()), 104)
    _check_eq("htsFile.fnidx.offset", Int(r.field_offset[index=9]()), 112)
    _check_eq("htsFile.bam_header.offset", Int(r.field_offset[index=10]()), 120)
    _check_eq("htsFile.filter.offset", Int(r.field_offset[index=11]()), 128)
    _check_eq("htsFile.__bf0.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_htsThreadPool() raises:
    comptime r = reflect[htsThreadPool]
    _check_eq("htsThreadPool.size", Int(size_of[htsThreadPool]()), 16)
    _check_eq("htsThreadPool.align", Int(align_of[htsThreadPool]()), 8)
    _check_eq("htsThreadPool.pool.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("htsThreadPool.qsize.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_hts_opt() raises:
    comptime r = reflect[hts_opt]
    _check_eq("hts_opt.size", Int(size_of[hts_opt]()), 32)
    _check_eq("hts_opt.align", Int(align_of[hts_opt]()), 8)
    _check_eq("hts_opt.arg.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_opt.opt.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hts_opt.val.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("hts_opt.next.offset", Int(r.field_offset[index=3]()), 24)


def test_layout_hts_pair_pos_t() raises:
    comptime r = reflect[hts_pair_pos_t]
    _check_eq("hts_pair_pos_t.size", Int(size_of[hts_pair_pos_t]()), 16)
    _check_eq("hts_pair_pos_t.align", Int(align_of[hts_pair_pos_t]()), 8)
    _check_eq("hts_pair_pos_t.beg.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_pair_pos_t.end.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_hts_pair64_t() raises:
    comptime r = reflect[hts_pair64_t]
    _check_eq("hts_pair64_t.size", Int(size_of[hts_pair64_t]()), 16)
    _check_eq("hts_pair64_t.align", Int(align_of[hts_pair64_t]()), 8)
    _check_eq("hts_pair64_t.u.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_pair64_t.v.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_hts_pair64_max_t() raises:
    comptime r = reflect[hts_pair64_max_t]
    _check_eq("hts_pair64_max_t.size", Int(size_of[hts_pair64_max_t]()), 24)
    _check_eq("hts_pair64_max_t.align", Int(align_of[hts_pair64_max_t]()), 8)
    _check_eq("hts_pair64_max_t.u.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_pair64_max_t.v.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hts_pair64_max_t.max.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_hts_reglist_t() raises:
    comptime r = reflect[hts_reglist_t]
    _check_eq("hts_reglist_t.size", Int(size_of[hts_reglist_t]()), 40)
    _check_eq("hts_reglist_t.align", Int(align_of[hts_reglist_t]()), 8)
    _check_eq("hts_reglist_t.reg.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_reglist_t.intervals.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hts_reglist_t.tid.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("hts_reglist_t.count.offset", Int(r.field_offset[index=3]()), 20)
    _check_eq("hts_reglist_t.min_beg.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("hts_reglist_t.max_end.offset", Int(r.field_offset[index=5]()), 32)


def test_layout_hts_itr_t__anon_struct_1() raises:
    comptime r = reflect[hts_itr_t__anon_struct_1]
    _check_eq("hts_itr_t__anon_struct_1.size", Int(size_of[hts_itr_t__anon_struct_1]()), 16)
    _check_eq("hts_itr_t__anon_struct_1.align", Int(align_of[hts_itr_t__anon_struct_1]()), 8)
    _check_eq("hts_itr_t__anon_struct_1.n.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_itr_t__anon_struct_1.m.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("hts_itr_t__anon_struct_1.a.offset", Int(r.field_offset[index=2]()), 8)


def test_layout_hts_itr_t() raises:
    comptime r = reflect[hts_itr_t]
    _check_eq("hts_itr_t.size", Int(size_of[hts_itr_t]()), 144)
    _check_eq("hts_itr_t.align", Int(align_of[hts_itr_t]()), 8)
    _check_eq("hts_itr_t.tid.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("hts_itr_t.n_off.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("hts_itr_t.i.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("hts_itr_t.n_reg.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("hts_itr_t.beg.offset", Int(r.field_offset[index=5]()), 24)
    _check_eq("hts_itr_t.end.offset", Int(r.field_offset[index=6]()), 32)
    _check_eq("hts_itr_t.reg_list.offset", Int(r.field_offset[index=7]()), 40)
    _check_eq("hts_itr_t.curr_tid.offset", Int(r.field_offset[index=8]()), 48)
    _check_eq("hts_itr_t.curr_reg.offset", Int(r.field_offset[index=9]()), 52)
    _check_eq("hts_itr_t.curr_intv.offset", Int(r.field_offset[index=10]()), 56)
    _check_eq("hts_itr_t.curr_beg.offset", Int(r.field_offset[index=11]()), 64)
    _check_eq("hts_itr_t.curr_end.offset", Int(r.field_offset[index=12]()), 72)
    _check_eq("hts_itr_t.curr_off.offset", Int(r.field_offset[index=13]()), 80)
    _check_eq("hts_itr_t.nocoor_off.offset", Int(r.field_offset[index=14]()), 88)
    _check_eq("hts_itr_t.off.offset", Int(r.field_offset[index=15]()), 96)
    _check_eq("hts_itr_t.readrec.offset", Int(r.field_offset[index=16]()), 104)
    _check_eq("hts_itr_t.seek.offset", Int(r.field_offset[index=17]()), 112)
    _check_eq("hts_itr_t.tell.offset", Int(r.field_offset[index=18]()), 120)
    _check_eq("hts_itr_t.bins.offset", Int(r.field_offset[index=19]()), 128)
    _check_eq("hts_itr_t.__bf0.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_probaln_par_t() raises:
    comptime r = reflect[probaln_par_t]
    _check_eq("probaln_par_t.size", Int(size_of[probaln_par_t]()), 12)
    _check_eq("probaln_par_t.align", Int(align_of[probaln_par_t]()), 4)
    _check_eq("probaln_par_t.d.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("probaln_par_t.e.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("probaln_par_t.bw.offset", Int(r.field_offset[index=2]()), 8)


def test_layout_bcf_hrec_t() raises:
    comptime r = reflect[bcf_hrec_t]
    _check_eq("bcf_hrec_t.size", Int(size_of[bcf_hrec_t]()), 48)
    _check_eq("bcf_hrec_t.align", Int(align_of[bcf_hrec_t]()), 8)
    _check_eq("bcf_hrec_t.type.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_hrec_t.key.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bcf_hrec_t.value.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("bcf_hrec_t.nkeys.offset", Int(r.field_offset[index=3]()), 24)
    _check_eq("bcf_hrec_t.keys.offset", Int(r.field_offset[index=4]()), 32)
    _check_eq("bcf_hrec_t.vals.offset", Int(r.field_offset[index=5]()), 40)


def test_layout_bcf_idinfo_t() raises:
    comptime r = reflect[bcf_idinfo_t]
    _check_eq("bcf_idinfo_t.size", Int(size_of[bcf_idinfo_t]()), 56)
    _check_eq("bcf_idinfo_t.align", Int(align_of[bcf_idinfo_t]()), 8)
    _check_eq("bcf_idinfo_t.info.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_idinfo_t.hrec.offset", Int(r.field_offset[index=1]()), 24)
    _check_eq("bcf_idinfo_t.id.offset", Int(r.field_offset[index=2]()), 48)


def test_layout_bcf_idpair_t() raises:
    comptime r = reflect[bcf_idpair_t]
    _check_eq("bcf_idpair_t.size", Int(size_of[bcf_idpair_t]()), 16)
    _check_eq("bcf_idpair_t.align", Int(align_of[bcf_idpair_t]()), 8)
    _check_eq("bcf_idpair_t.key.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_idpair_t.val.offset", Int(r.field_offset[index=1]()), 8)


def test_layout_bcf_hdr_t() raises:
    comptime r = reflect[bcf_hdr_t]
    _check_eq("bcf_hdr_t.size", Int(size_of[bcf_hdr_t]()), 168)
    _check_eq("bcf_hdr_t.align", Int(align_of[bcf_hdr_t]()), 8)
    _check_eq("bcf_hdr_t.n.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_hdr_t.id.offset", Int(r.field_offset[index=1]()), 16)
    _check_eq("bcf_hdr_t.dict.offset", Int(r.field_offset[index=2]()), 40)
    _check_eq("bcf_hdr_t.samples.offset", Int(r.field_offset[index=3]()), 64)
    _check_eq("bcf_hdr_t.hrec.offset", Int(r.field_offset[index=4]()), 72)
    _check_eq("bcf_hdr_t.nhrec.offset", Int(r.field_offset[index=5]()), 80)
    _check_eq("bcf_hdr_t.dirty.offset", Int(r.field_offset[index=6]()), 84)
    _check_eq("bcf_hdr_t.ntransl.offset", Int(r.field_offset[index=7]()), 88)
    _check_eq("bcf_hdr_t.transl.offset", Int(r.field_offset[index=8]()), 96)
    _check_eq("bcf_hdr_t.nsamples_ori.offset", Int(r.field_offset[index=9]()), 112)
    _check_eq("bcf_hdr_t.keep_samples.offset", Int(r.field_offset[index=10]()), 120)
    _check_eq("bcf_hdr_t.mem.offset", Int(r.field_offset[index=11]()), 128)
    _check_eq("bcf_hdr_t.m.offset", Int(r.field_offset[index=12]()), 152)


def test_layout_bcf_variant_t() raises:
    comptime r = reflect[bcf_variant_t]
    _check_eq("bcf_variant_t.size", Int(size_of[bcf_variant_t]()), 8)
    _check_eq("bcf_variant_t.align", Int(align_of[bcf_variant_t]()), 4)
    _check_eq("bcf_variant_t.type.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_variant_t.n.offset", Int(r.field_offset[index=1]()), 4)


def test_layout_bcf_fmt_t() raises:
    comptime r = reflect[bcf_fmt_t]
    _check_eq("bcf_fmt_t.size", Int(size_of[bcf_fmt_t]()), 32)
    _check_eq("bcf_fmt_t.align", Int(align_of[bcf_fmt_t]()), 8)
    _check_eq("bcf_fmt_t.id.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_fmt_t.n.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("bcf_fmt_t.size.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("bcf_fmt_t.type.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("bcf_fmt_t.p.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("bcf_fmt_t.p_len.offset", Int(r.field_offset[index=5]()), 24)
    _check_eq("bcf_fmt_t.__bf0.offset", Int(r.field_offset[index=6]()), 28)


def test_layout_bcf_info_t() raises:
    comptime r = reflect[bcf_info_t]
    _check_eq("bcf_info_t.size", Int(size_of[bcf_info_t]()), 40)
    _check_eq("bcf_info_t.align", Int(align_of[bcf_info_t]()), 8)
    _check_eq("bcf_info_t.key.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_info_t.type.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("bcf_info_t.v1.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("bcf_info_t.vptr.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("bcf_info_t.vptr_len.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("bcf_info_t.len.offset", Int(r.field_offset[index=6]()), 32)
    _check_eq("bcf_info_t.__bf0.offset", Int(r.field_offset[index=5]()), 28)


def test_layout_bcf_dec_t() raises:
    comptime r = reflect[bcf_dec_t]
    _check_eq("bcf_dec_t.size", Int(size_of[bcf_dec_t]()), 104)
    _check_eq("bcf_dec_t.align", Int(align_of[bcf_dec_t]()), 8)
    _check_eq("bcf_dec_t.m_fmt.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_dec_t.m_info.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("bcf_dec_t.m_id.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("bcf_dec_t.m_als.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("bcf_dec_t.m_allele.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("bcf_dec_t.m_flt.offset", Int(r.field_offset[index=5]()), 20)
    _check_eq("bcf_dec_t.n_flt.offset", Int(r.field_offset[index=6]()), 24)
    _check_eq("bcf_dec_t.flt.offset", Int(r.field_offset[index=7]()), 32)
    _check_eq("bcf_dec_t.id.offset", Int(r.field_offset[index=8]()), 40)
    _check_eq("bcf_dec_t.als.offset", Int(r.field_offset[index=9]()), 48)
    _check_eq("bcf_dec_t.allele.offset", Int(r.field_offset[index=10]()), 56)
    _check_eq("bcf_dec_t.info.offset", Int(r.field_offset[index=11]()), 64)
    _check_eq("bcf_dec_t.fmt.offset", Int(r.field_offset[index=12]()), 72)
    _check_eq("bcf_dec_t.var_.offset", Int(r.field_offset[index=13]()), 80)
    _check_eq("bcf_dec_t.n_var.offset", Int(r.field_offset[index=14]()), 88)
    _check_eq("bcf_dec_t.var_type.offset", Int(r.field_offset[index=15]()), 92)
    _check_eq("bcf_dec_t.shared_dirty.offset", Int(r.field_offset[index=16]()), 96)
    _check_eq("bcf_dec_t.indiv_dirty.offset", Int(r.field_offset[index=17]()), 100)


def test_layout_bcf1_t() raises:
    comptime r = reflect[bcf1_t]
    _check_eq("bcf1_t.size", Int(size_of[bcf1_t]()), 208)
    _check_eq("bcf1_t.align", Int(align_of[bcf1_t]()), 8)
    _check_eq("bcf1_t.pos.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf1_t.rlen.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bcf1_t.rid.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("bcf1_t.qual.offset", Int(r.field_offset[index=3]()), 20)
    _check_eq("bcf1_t.shared.offset", Int(r.field_offset[index=6]()), 32)
    _check_eq("bcf1_t.indiv.offset", Int(r.field_offset[index=7]()), 56)
    _check_eq("bcf1_t.d.offset", Int(r.field_offset[index=8]()), 80)
    _check_eq("bcf1_t.max_unpack.offset", Int(r.field_offset[index=9]()), 184)
    _check_eq("bcf1_t.unpacked.offset", Int(r.field_offset[index=10]()), 188)
    _check_eq("bcf1_t.unpack_size.offset", Int(r.field_offset[index=11]()), 192)
    _check_eq("bcf1_t.errcode.offset", Int(r.field_offset[index=12]()), 204)
    _check_eq("bcf1_t.__bf0.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("bcf1_t.__bf1.offset", Int(r.field_offset[index=5]()), 28)


def test_layout_sam_hdr_t() raises:
    comptime r = reflect[sam_hdr_t]
    _check_eq("sam_hdr_t.size", Int(size_of[sam_hdr_t]()), 72)
    _check_eq("sam_hdr_t.align", Int(align_of[sam_hdr_t]()), 8)
    _check_eq("sam_hdr_t.n_targets.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("sam_hdr_t.ignore_sam_err.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("sam_hdr_t.l_text.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("sam_hdr_t.target_len.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("sam_hdr_t.cigar_tab.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("sam_hdr_t.target_name.offset", Int(r.field_offset[index=5]()), 32)
    _check_eq("sam_hdr_t.text.offset", Int(r.field_offset[index=6]()), 40)
    _check_eq("sam_hdr_t.sdict.offset", Int(r.field_offset[index=7]()), 48)
    _check_eq("sam_hdr_t.hrecs.offset", Int(r.field_offset[index=8]()), 56)
    _check_eq("sam_hdr_t.ref_count.offset", Int(r.field_offset[index=9]()), 64)


def test_layout_bam1_core_t() raises:
    comptime r = reflect[bam1_core_t]
    _check_eq("bam1_core_t.size", Int(size_of[bam1_core_t]()), 48)
    _check_eq("bam1_core_t.align", Int(align_of[bam1_core_t]()), 8)
    _check_eq("bam1_core_t.pos.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bam1_core_t.tid.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bam1_core_t.bin.offset", Int(r.field_offset[index=2]()), 12)
    _check_eq("bam1_core_t.qual.offset", Int(r.field_offset[index=3]()), 14)
    _check_eq("bam1_core_t.l_extranul.offset", Int(r.field_offset[index=4]()), 15)
    _check_eq("bam1_core_t.flag.offset", Int(r.field_offset[index=5]()), 16)
    _check_eq("bam1_core_t.l_qname.offset", Int(r.field_offset[index=6]()), 18)
    _check_eq("bam1_core_t.n_cigar.offset", Int(r.field_offset[index=7]()), 20)
    _check_eq("bam1_core_t.l_qseq.offset", Int(r.field_offset[index=8]()), 24)
    _check_eq("bam1_core_t.mtid.offset", Int(r.field_offset[index=9]()), 28)
    _check_eq("bam1_core_t.mpos.offset", Int(r.field_offset[index=10]()), 32)
    _check_eq("bam1_core_t.isize.offset", Int(r.field_offset[index=11]()), 40)


def test_layout_bam1_t() raises:
    comptime r = reflect[bam1_t]
    _check_eq("bam1_t.size", Int(size_of[bam1_t]()), 80)
    _check_eq("bam1_t.align", Int(align_of[bam1_t]()), 8)
    _check_eq("bam1_t.core.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bam1_t.id.offset", Int(r.field_offset[index=1]()), 48)
    _check_eq("bam1_t.data.offset", Int(r.field_offset[index=2]()), 56)
    _check_eq("bam1_t.l_data.offset", Int(r.field_offset[index=3]()), 64)
    _check_eq("bam1_t.m_data.offset", Int(r.field_offset[index=4]()), 68)
    _check_eq("bam1_t.__bf0.offset", Int(r.field_offset[index=5]()), 72)


def test_layout_bam_pileup1_t() raises:
    comptime r = reflect[bam_pileup1_t]
    _check_eq("bam_pileup1_t.size", Int(size_of[bam_pileup1_t]()), 40)
    _check_eq("bam_pileup1_t.align", Int(align_of[bam_pileup1_t]()), 8)
    _check_eq("bam_pileup1_t.b.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bam_pileup1_t.qpos.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bam_pileup1_t.indel.offset", Int(r.field_offset[index=2]()), 12)
    _check_eq("bam_pileup1_t.level.offset", Int(r.field_offset[index=3]()), 16)
    _check_eq("bam_pileup1_t.cd.offset", Int(r.field_offset[index=5]()), 24)
    _check_eq("bam_pileup1_t.cigar_ind.offset", Int(r.field_offset[index=6]()), 32)
    _check_eq("bam_pileup1_t.__bf0.offset", Int(r.field_offset[index=4]()), 20)


def test_layout_hts_base_mod() raises:
    comptime r = reflect[hts_base_mod]
    _check_eq("hts_base_mod.size", Int(size_of[hts_base_mod]()), 16)
    _check_eq("hts_base_mod.align", Int(align_of[hts_base_mod]()), 4)
    _check_eq("hts_base_mod.modified_base.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hts_base_mod.canonical_base.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("hts_base_mod.strand.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("hts_base_mod.qual.offset", Int(r.field_offset[index=3]()), 12)


def test_layout_hFILE() raises:
    comptime r = reflect[hFILE]
    _check_eq("hFILE.size", Int(size_of[hFILE]()), 56)
    _check_eq("hFILE.align", Int(align_of[hFILE]()), 8)
    _check_eq("hFILE.buffer.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("hFILE.begin.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("hFILE.end.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("hFILE.limit.offset", Int(r.field_offset[index=3]()), 24)
    _check_eq("hFILE.backend.offset", Int(r.field_offset[index=4]()), 32)
    _check_eq("hFILE.offset.offset", Int(r.field_offset[index=5]()), 40)
    _check_eq("hFILE.has_errno.offset", Int(r.field_offset[index=7]()), 52)
    _check_eq("hFILE.__bf0.offset", Int(r.field_offset[index=6]()), 48)


def test_layout_cram_method_details() raises:
    comptime r = reflect[cram_method_details]
    _check_eq("cram_method_details.size", Int(size_of[cram_method_details]()), 40)
    _check_eq("cram_method_details.align", Int(align_of[cram_method_details]()), 4)
    _check_eq("cram_method_details.method.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("cram_method_details.level.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("cram_method_details.order.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("cram_method_details.rle.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("cram_method_details.pack.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("cram_method_details.stripe.offset", Int(r.field_offset[index=5]()), 20)
    _check_eq("cram_method_details.cat.offset", Int(r.field_offset[index=6]()), 24)
    _check_eq("cram_method_details.nosz.offset", Int(r.field_offset[index=7]()), 28)
    _check_eq("cram_method_details.Nway.offset", Int(r.field_offset[index=8]()), 32)
    _check_eq("cram_method_details.ext.offset", Int(r.field_offset[index=9]()), 36)


def test_layout_BGZF() raises:
    comptime r = reflect[BGZF]
    _check_eq("BGZF.size", Int(size_of[BGZF]()), 112)
    _check_eq("BGZF.align", Int(align_of[BGZF]()), 8)
    _check_eq("BGZF.cache_size.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("BGZF.block_length.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("BGZF.block_clength.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("BGZF.block_offset.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("BGZF.block_address.offset", Int(r.field_offset[index=5]()), 24)
    _check_eq("BGZF.uncompressed_address.offset", Int(r.field_offset[index=6]()), 32)
    _check_eq("BGZF.uncompressed_block.offset", Int(r.field_offset[index=7]()), 40)
    _check_eq("BGZF.compressed_block.offset", Int(r.field_offset[index=8]()), 48)
    _check_eq("BGZF.cache.offset", Int(r.field_offset[index=9]()), 56)
    _check_eq("BGZF.fp.offset", Int(r.field_offset[index=10]()), 64)
    _check_eq("BGZF.mt.offset", Int(r.field_offset[index=11]()), 72)
    _check_eq("BGZF.idx.offset", Int(r.field_offset[index=12]()), 80)
    _check_eq("BGZF.idx_build_otf.offset", Int(r.field_offset[index=13]()), 88)
    _check_eq("BGZF.gz_stream.offset", Int(r.field_offset[index=14]()), 96)
    _check_eq("BGZF.seeked.offset", Int(r.field_offset[index=15]()), 104)
    _check_eq("BGZF.__bf0.offset", Int(r.field_offset[index=0]()), 0)


def test_layout_tbx_conf_t() raises:
    comptime r = reflect[tbx_conf_t]
    _check_eq("tbx_conf_t.size", Int(size_of[tbx_conf_t]()), 24)
    _check_eq("tbx_conf_t.align", Int(align_of[tbx_conf_t]()), 4)
    _check_eq("tbx_conf_t.preset.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("tbx_conf_t.sc.offset", Int(r.field_offset[index=1]()), 4)
    _check_eq("tbx_conf_t.bc.offset", Int(r.field_offset[index=2]()), 8)
    _check_eq("tbx_conf_t.ec.offset", Int(r.field_offset[index=3]()), 12)
    _check_eq("tbx_conf_t.meta_char.offset", Int(r.field_offset[index=4]()), 16)
    _check_eq("tbx_conf_t.line_skip.offset", Int(r.field_offset[index=5]()), 20)


def test_layout_tbx_t() raises:
    comptime r = reflect[tbx_t]
    _check_eq("tbx_t.size", Int(size_of[tbx_t]()), 40)
    _check_eq("tbx_t.align", Int(align_of[tbx_t]()), 8)
    _check_eq("tbx_t.conf.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("tbx_t.idx.offset", Int(r.field_offset[index=1]()), 24)
    _check_eq("tbx_t.dict.offset", Int(r.field_offset[index=2]()), 32)


def test_layout_bcf_sr_regions_t() raises:
    comptime r = reflect[bcf_sr_regions_t]
    _check_eq("bcf_sr_regions_t.size", Int(size_of[bcf_sr_regions_t]()), 208)
    _check_eq("bcf_sr_regions_t.align", Int(align_of[bcf_sr_regions_t]()), 8)
    _check_eq("bcf_sr_regions_t.tbx.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_sr_regions_t.itr.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bcf_sr_regions_t.line.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("bcf_sr_regions_t.file.offset", Int(r.field_offset[index=3]()), 40)
    _check_eq("bcf_sr_regions_t.fname.offset", Int(r.field_offset[index=4]()), 48)
    _check_eq("bcf_sr_regions_t.is_bin.offset", Int(r.field_offset[index=5]()), 56)
    _check_eq("bcf_sr_regions_t.als.offset", Int(r.field_offset[index=6]()), 64)
    _check_eq("bcf_sr_regions_t.als_str.offset", Int(r.field_offset[index=7]()), 72)
    _check_eq("bcf_sr_regions_t.nals.offset", Int(r.field_offset[index=8]()), 96)
    _check_eq("bcf_sr_regions_t.mals.offset", Int(r.field_offset[index=9]()), 100)
    _check_eq("bcf_sr_regions_t.als_type.offset", Int(r.field_offset[index=10]()), 104)
    _check_eq("bcf_sr_regions_t.missed_reg_handler.offset", Int(r.field_offset[index=11]()), 112)
    _check_eq("bcf_sr_regions_t.missed_reg_data.offset", Int(r.field_offset[index=12]()), 120)
    _check_eq("bcf_sr_regions_t.regs.offset", Int(r.field_offset[index=13]()), 128)
    _check_eq("bcf_sr_regions_t.seq_hash.offset", Int(r.field_offset[index=14]()), 136)
    _check_eq("bcf_sr_regions_t.seq_names.offset", Int(r.field_offset[index=15]()), 144)
    _check_eq("bcf_sr_regions_t.nseqs.offset", Int(r.field_offset[index=16]()), 152)
    _check_eq("bcf_sr_regions_t.iseq.offset", Int(r.field_offset[index=17]()), 156)
    _check_eq("bcf_sr_regions_t.start.offset", Int(r.field_offset[index=18]()), 160)
    _check_eq("bcf_sr_regions_t.end.offset", Int(r.field_offset[index=19]()), 168)
    _check_eq("bcf_sr_regions_t.prev_seq.offset", Int(r.field_offset[index=20]()), 176)
    _check_eq("bcf_sr_regions_t.prev_start.offset", Int(r.field_offset[index=21]()), 184)
    _check_eq("bcf_sr_regions_t.prev_end.offset", Int(r.field_offset[index=22]()), 192)
    _check_eq("bcf_sr_regions_t.overlap.offset", Int(r.field_offset[index=23]()), 200)


def test_layout_bcf_sr_t() raises:
    comptime r = reflect[bcf_sr_t]
    _check_eq("bcf_sr_t.size", Int(size_of[bcf_sr_t]()), 96)
    _check_eq("bcf_sr_t.align", Int(align_of[bcf_sr_t]()), 8)
    _check_eq("bcf_sr_t.file.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_sr_t.tbx_idx.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bcf_sr_t.bcf_idx.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("bcf_sr_t.header.offset", Int(r.field_offset[index=3]()), 24)
    _check_eq("bcf_sr_t.itr.offset", Int(r.field_offset[index=4]()), 32)
    _check_eq("bcf_sr_t.fname.offset", Int(r.field_offset[index=5]()), 40)
    _check_eq("bcf_sr_t.buffer.offset", Int(r.field_offset[index=6]()), 48)
    _check_eq("bcf_sr_t.nbuffer.offset", Int(r.field_offset[index=7]()), 56)
    _check_eq("bcf_sr_t.mbuffer.offset", Int(r.field_offset[index=8]()), 60)
    _check_eq("bcf_sr_t.nfilter_ids.offset", Int(r.field_offset[index=9]()), 64)
    _check_eq("bcf_sr_t.filter_ids.offset", Int(r.field_offset[index=10]()), 72)
    _check_eq("bcf_sr_t.samples.offset", Int(r.field_offset[index=11]()), 80)
    _check_eq("bcf_sr_t.n_smpl.offset", Int(r.field_offset[index=12]()), 88)


def test_layout_bcf_srs_t() raises:
    comptime r = reflect[bcf_srs_t]
    _check_eq("bcf_srs_t.size", Int(size_of[bcf_srs_t]()), 144)
    _check_eq("bcf_srs_t.align", Int(align_of[bcf_srs_t]()), 8)
    _check_eq("bcf_srs_t.collapse.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("bcf_srs_t.apply_filters.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("bcf_srs_t.require_index.offset", Int(r.field_offset[index=2]()), 16)
    _check_eq("bcf_srs_t.max_unpack.offset", Int(r.field_offset[index=3]()), 20)
    _check_eq("bcf_srs_t.has_line.offset", Int(r.field_offset[index=4]()), 24)
    _check_eq("bcf_srs_t.errnum.offset", Int(r.field_offset[index=5]()), 32)
    _check_eq("bcf_srs_t.readers.offset", Int(r.field_offset[index=6]()), 40)
    _check_eq("bcf_srs_t.nreaders.offset", Int(r.field_offset[index=7]()), 48)
    _check_eq("bcf_srs_t.streaming.offset", Int(r.field_offset[index=8]()), 52)
    _check_eq("bcf_srs_t.explicit_regs.offset", Int(r.field_offset[index=9]()), 56)
    _check_eq("bcf_srs_t.samples.offset", Int(r.field_offset[index=10]()), 64)
    _check_eq("bcf_srs_t.regions.offset", Int(r.field_offset[index=11]()), 72)
    _check_eq("bcf_srs_t.targets.offset", Int(r.field_offset[index=12]()), 80)
    _check_eq("bcf_srs_t.targets_als.offset", Int(r.field_offset[index=13]()), 88)
    _check_eq("bcf_srs_t.targets_exclude.offset", Int(r.field_offset[index=14]()), 92)
    _check_eq("bcf_srs_t.tmps.offset", Int(r.field_offset[index=15]()), 96)
    _check_eq("bcf_srs_t.n_smpl.offset", Int(r.field_offset[index=16]()), 120)
    _check_eq("bcf_srs_t.n_threads.offset", Int(r.field_offset[index=17]()), 124)
    _check_eq("bcf_srs_t.p.offset", Int(r.field_offset[index=18]()), 128)
    _check_eq("bcf_srs_t.aux.offset", Int(r.field_offset[index=19]()), 136)


def test_layout_kbitset_t() raises:
    comptime r = reflect[kbitset_t]
    _check_eq("kbitset_t.size", Int(size_of[kbitset_t]()), 24)
    _check_eq("kbitset_t.align", Int(align_of[kbitset_t]()), 8)
    _check_eq("kbitset_t.n.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("kbitset_t.n_max.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("kbitset_t.b.offset", Int(r.field_offset[index=2]()), 16)


def test_layout_kbitset_iter_t() raises:
    comptime r = reflect[kbitset_iter_t]
    _check_eq("kbitset_iter_t.size", Int(size_of[kbitset_iter_t]()), 24)
    _check_eq("kbitset_iter_t.align", Int(align_of[kbitset_iter_t]()), 8)
    _check_eq("kbitset_iter_t.mask.offset", Int(r.field_offset[index=0]()), 0)
    _check_eq("kbitset_iter_t.elt.offset", Int(r.field_offset[index=1]()), 8)
    _check_eq("kbitset_iter_t.i.offset", Int(r.field_offset[index=2]()), 16)


def main() raises:
    TestSuite.discover_tests[__functions_in_module()]().run()
